"""Code templates for the python-stdlib-crud-api stack.

Generation is capability-gated: a route or storage method exists only if the spec
declares the matching functional requirement. Output is deterministic — a pure
function of the spec.
"""

from __future__ import annotations

from pmpe.domain.models import Entity, GeneratedFile, MvpSpec
from pmpe.stacks import (
    capabilities_for,
    collection_route,
    entity_var,
    has_auth,
    has_health,
    table_name,
)

_SQL_TYPES = {"string": "TEXT", "text": "TEXT", "int": "INTEGER", "bool": "INTEGER",
              "timestamp": "TEXT"}


def _column_def(name: str, sql_type: str, required: bool, default: str | None) -> str:
    parts = [name, sql_type]
    if required:
        parts.append("NOT NULL")
    if default is not None:
        parts.append(f"DEFAULT '{default}'")
    return " ".join(parts)


def app_init_module(spec: MvpSpec) -> str:
    return f'"""{spec.product_name} — generated by PM Production Engineering OS."""\n'


def storage_module(spec: MvpSpec) -> str:
    lines = [
        '"""Storage layer: SQLite, parameterized queries, one writer lock."""',
        "",
        "import sqlite3",
        "import threading",
        "from datetime import datetime, timezone",
        "",
        "",
        "def _utc_now():",
        '    return datetime.now(timezone.utc).isoformat()',
        "",
        "",
        "class Storage:",
        '    """SQLite-backed persistence. The db_path comes from configuration,',
        '    never from request data."""',
        "",
        "    def __init__(self, db_path):",
        "        self._conn = sqlite3.connect(db_path, check_same_thread=False)",
        "        self._conn.row_factory = sqlite3.Row",
        "        self._lock = threading.Lock()",
    ]
    for entity in spec.entities:
        columns = ", ".join(
            [_column_def(f.name, _SQL_TYPES.get(f.type, "TEXT"), f.required, f.default)
             for f in entity.fields]
        )
        lines += [
            "        self._conn.execute(",
            f'            "CREATE TABLE IF NOT EXISTS {table_name(entity)} ("',
            '            "id INTEGER PRIMARY KEY AUTOINCREMENT, "',
            f'            "{columns}, "',
            '            "created_at TEXT NOT NULL, updated_at TEXT NOT NULL)"',
            "        )",
        ]
    lines += [
        "        self._conn.commit()",
        "",
        "    def close(self):",
        "        self._conn.close()",
    ]
    for entity in spec.entities:
        lines += _storage_entity_methods(spec, entity)
    return "\n".join(lines) + "\n"


def _storage_entity_methods(spec: MvpSpec, entity: Entity) -> list[str]:
    caps = capabilities_for(spec, entity)
    var = entity_var(entity)
    table = table_name(entity)
    field_names = [f.name for f in entity.fields]
    insert_cols = ", ".join(field_names + ["created_at", "updated_at"])
    placeholders = ", ".join(["?"] * (len(field_names) + 2))
    value_exprs: list[str] = []
    for f in entity.fields:
        if f.default is not None:
            value_exprs.append(f'fields.get("{f.name}", "{f.default}")')
        else:
            value_exprs.append(f'fields.get("{f.name}")')
    values = ", ".join(value_exprs)

    lines: list[str] = []
    # get_* is always generated: create/update return the stored row through it
    lines += [
        "",
        f"    def get_{var}(self, {var}_id):",
        "        row = self._conn.execute(",
        f'            "SELECT * FROM {table} WHERE id = ?", ({var}_id,)',
        "        ).fetchone()",
        "        return dict(row) if row else None",
    ]
    if "entity.create" in caps:
        lines += [
            "",
            f"    def create_{var}(self, fields):",
            "        now = _utc_now()",
            "        with self._lock:",
            "            cur = self._conn.execute(",
            f'                "INSERT INTO {table} ({insert_cols}) "',
            f'                "VALUES ({placeholders})",',
            f"                ({values}, now, now),",
            "            )",
            "            self._conn.commit()",
            f"        return self.get_{var}(cur.lastrowid)",
        ]
    if "entity.list" in caps:
        filter_field = "status" if "status" in field_names else None
        if filter_field:
            lines += [
                "",
                f"    def list_{table}(self, {filter_field}=None):",
                f"        if {filter_field} is None:",
                "            rows = self._conn.execute(",
                f'                "SELECT * FROM {table} ORDER BY id DESC"',
                "            ).fetchall()",
                "        else:",
                "            rows = self._conn.execute(",
                f'                "SELECT * FROM {table} WHERE {filter_field} = ? '
                'ORDER BY id DESC",',
                f"                ({filter_field},),",
                "            ).fetchall()",
                "        return [dict(r) for r in rows]",
            ]
        else:
            lines += [
                "",
                f"    def list_{table}(self):",
                "        rows = self._conn.execute(",
                f'            "SELECT * FROM {table} ORDER BY id DESC"',
                "        ).fetchall()",
                "        return [dict(r) for r in rows]",
            ]
    if "entity.update" in caps:
        allowed = ", ".join(f'"{n}"' for n in field_names)
        lines += [
            "",
            f"    def update_{var}(self, {var}_id, fields):",
            f"        allowed = ({allowed},)",
            "        changes = {k: v for k, v in fields.items() if k in allowed}",
            "        if not changes:",
            f"            return self.get_{var}({var}_id)",
            '        assignments = ", ".join(k + " = ?" for k in sorted(changes))',
            "        values = [changes[k] for k in sorted(changes)]",
            "        with self._lock:",
            "            cur = self._conn.execute(",
            f'                "UPDATE {table} SET " + assignments + ", updated_at = ? '
            'WHERE id = ?",',
            f"                (*values, _utc_now(), {var}_id),",
            "            )",
            "            self._conn.commit()",
            "        if cur.rowcount == 0:",
            "            return None",
            f"        return self.get_{var}({var}_id)",
        ]
    if "entity.delete" in caps:
        lines += [
            "",
            f"    def delete_{var}(self, {var}_id):",
            "        with self._lock:",
            "            cur = self._conn.execute(",
            f'                "DELETE FROM {table} WHERE id = ?", ({var}_id,)',
            "            )",
            "            self._conn.commit()",
            "        return cur.rowcount > 0",
        ]
    return lines


def auth_module() -> str:
    return '''"""Bearer-token authentication.

The token is injected via the APP_TOKEN environment variable at deploy time.
It is never stored in code, configuration files, or logs.
"""

import hmac
import os

TOKEN_ENV = "APP_TOKEN"


def expected_token():
    return os.environ.get(TOKEN_ENV, "")


def token_from_header(header):
    if not header:
        return ""
    parts = header.split(" ", 1)
    if len(parts) != 2 or parts[0].lower() != "bearer":
        return ""
    return parts[1].strip()


def verify_token(candidate):
    expected = expected_token()
    if not expected or not candidate:
        return False
    return hmac.compare_digest(candidate, expected)
'''


def api_module(spec: MvpSpec) -> str:
    auth = has_auth(spec)
    lines = [
        '"""HTTP API: routing, request validation, JSON error contract."""',
        "",
        "import json",
        "import logging",
        "from http.server import BaseHTTPRequestHandler",
        "from urllib.parse import parse_qs, urlsplit",
        "",
    ]
    if auth:
        lines += ["from app import auth", ""]
    lines += [
        f'SERVICE_NAME = "{spec.product_name}"',
        'logger = logging.getLogger(SERVICE_NAME.lower())',
        "",
        "",
        "class ApiHandler(BaseHTTPRequestHandler):",
        "",
        "    def log_message(self, fmt, *args):",
        '        logger.debug("%s " + fmt, self.address_string(), *args)',
        "",
        "    def _send_json(self, status, payload):",
        '        body = json.dumps(payload).encode("utf-8")',
        "        self.send_response(status)",
        '        self.send_header("Content-Type", "application/json")',
        '        self.send_header("Content-Length", str(len(body)))',
        "        self.end_headers()",
        "        self.wfile.write(body)",
        "",
        "    def _send_empty(self, status):",
        "        self.send_response(status)",
        '        self.send_header("Content-Length", "0")',
        "        self.end_headers()",
        "",
        "    def _read_body(self):",
        '        length = int(self.headers.get("Content-Length") or 0)',
        '        raw = self.rfile.read(length) if length else b""',
        "        if not raw:",
        "            return {}",
        "        try:",
        '            data = json.loads(raw.decode("utf-8"))',
        "        except (UnicodeDecodeError, ValueError):",
        "            return None",
        "        return data if isinstance(data, dict) else None",
        "",
        "    def _split_path(self):",
        "        parsed = urlsplit(self.path)",
        '        path = parsed.path.rstrip("/") or "/"',
        "        return path, parse_qs(parsed.query)",
        "",
        "    def _match_item(self, path, route):",
        '        prefix = route + "/"',
        "        if path.startswith(prefix):",
        "            tail = path[len(prefix):]",
        "            if tail.isdigit():",
        "                return int(tail)",
        "        return None",
        "",
        "    def _storage(self):",
        "        return self.server.storage",
    ]
    if auth:
        lines += [
            "",
            "    def _authorized(self):",
            '        token = auth.token_from_header(self.headers.get("Authorization"))',
            "        return auth.verify_token(token)",
            "",
            "    def _reject_unauthorized(self):",
            "        self._send_json(",
            '            401, {"error": {"message": "missing or invalid bearer token"}}',
            "        )",
        ]
    lines += _api_get(spec, auth)
    lines += _api_post(spec, auth)
    lines += _api_patch(spec, auth)
    lines += _api_delete(spec, auth)
    return "\n".join(lines) + "\n"


def _guard(auth: bool) -> list[str]:
    if not auth:
        return []
    return [
        "            if not self._authorized():",
        "                self._reject_unauthorized()",
        "                return",
    ]


def _api_get(spec: MvpSpec, auth: bool) -> list[str]:
    lines = ["", "    def do_GET(self):", "        path, query = self._split_path()"]
    if has_health(spec):
        lines += [
            '        if path == "/health":',
            '            self._send_json(200, {"status": "ok", "service": SERVICE_NAME})',
            "            return",
        ]
    for entity in spec.entities:
        caps = capabilities_for(spec, entity)
        var, route, table = entity_var(entity), collection_route(entity), table_name(entity)
        has_status = any(f.name == "status" for f in entity.fields)
        if "entity.list" in caps:
            lines += [f'        if path == "{route}":'] + _guard(auth)
            if has_status:
                lines += [
                    f'            status = query.get("status", [None])[0]',
                    f"            self._send_json(200, self._storage().list_{table}"
                    "(status=status))",
                ]
            else:
                lines += [f"            self._send_json(200, self._storage().list_{table}())"]
            lines += ["            return"]
        if "entity.read" in caps:
            lines += [
                f'        {var}_id = self._match_item(path, "{route}")',
                f"        if {var}_id is not None:",
            ] + _guard(auth) + [
                f"            {var} = self._storage().get_{var}({var}_id)",
                f"            if {var} is None:",
                f'                self._send_json(404, {{"error": {{"message": '
                f'"{var} not found"}}}})',
                "            else:",
                f"                self._send_json(200, {var})",
                "            return",
            ]
    lines += ['        self._send_json(404, {"error": {"message": "not found"}})']
    return lines


def _api_post(spec: MvpSpec, auth: bool) -> list[str]:
    creatable = [e for e in spec.entities if "entity.create" in capabilities_for(spec, e)]
    if not creatable:
        return []
    lines = ["", "    def do_POST(self):", "        path, _query = self._split_path()"]
    for entity in creatable:
        var, route = entity_var(entity), collection_route(entity)
        allowed = ", ".join(f'"{f.name}"' for f in entity.fields)
        required = [f.name for f in entity.fields if f.required]
        lines += [f'        if path == "{route}":'] + _guard(auth) + [
            "            body = self._read_body()",
            "            if body is None:",
            '                self._send_json(400, {"error": {"message": "invalid JSON '
            'body"}})',
            "                return",
            f"            allowed = ({allowed},)",
            "            unknown = sorted(k for k in body if k not in allowed)",
            "            if unknown:",
            "                self._send_json(",
            '                    400,',
            '                    {"error": {"field": unknown[0], "message": "unknown '
            'field"}},',
            "                )",
            "                return",
        ]
        for name in required:
            lines += [
                f'            if not str(body.get("{name}") or "").strip():',
                "                self._send_json(",
                "                    400,",
                f'                    {{"error": {{"field": "{name}", "message": '
                f'"{name} is required"}}}},',
                "                )",
                "                return",
            ]
        lines += [
            f"            created = self._storage().create_{var}(body)",
            "            self._send_json(201, created)",
            "            return",
        ]
    lines += ['        self._send_json(404, {"error": {"message": "not found"}})']
    return lines


def _api_patch(spec: MvpSpec, auth: bool) -> list[str]:
    updatable = [e for e in spec.entities if "entity.update" in capabilities_for(spec, e)]
    if not updatable:
        return []
    lines = ["", "    def do_PATCH(self):", "        path, _query = self._split_path()"]
    for entity in updatable:
        var, route = entity_var(entity), collection_route(entity)
        allowed = ", ".join(f'"{f.name}"' for f in entity.fields)
        lines += [
            f'        {var}_id = self._match_item(path, "{route}")',
            f"        if {var}_id is not None:",
        ] + _guard(auth) + [
            "            body = self._read_body()",
            "            if body is None:",
            '                self._send_json(400, {"error": {"message": "invalid JSON '
            'body"}})',
            "                return",
            f"            allowed = ({allowed},)",
            "            unknown = sorted(k for k in body if k not in allowed)",
            "            if unknown:",
            "                self._send_json(",
            "                    400,",
            '                    {"error": {"field": unknown[0], "message": "unknown '
            'field"}},',
            "                )",
            "                return",
            f"            updated = self._storage().update_{var}({var}_id, body)",
            "            if updated is None:",
            f'                self._send_json(404, {{"error": {{"message": '
            f'"{var} not found"}}}})',
            "            else:",
            "                self._send_json(200, updated)",
            "            return",
        ]
    lines += ['        self._send_json(404, {"error": {"message": "not found"}})']
    return lines


def _api_delete(spec: MvpSpec, auth: bool) -> list[str]:
    deletable = [e for e in spec.entities if "entity.delete" in capabilities_for(spec, e)]
    if not deletable:
        return []
    lines = ["", "    def do_DELETE(self):", "        path, _query = self._split_path()"]
    for entity in deletable:
        var, route = entity_var(entity), collection_route(entity)
        lines += [
            f'        {var}_id = self._match_item(path, "{route}")',
            f"        if {var}_id is not None:",
        ] + _guard(auth) + [
            f"            if self._storage().delete_{var}({var}_id):",
            "                self._send_empty(204)",
            "            else:",
            f'                self._send_json(404, {{"error": {{"message": '
            f'"{var} not found"}}}})',
            "            return",
        ]
    lines += ['        self._send_json(404, {"error": {"message": "not found"}})']
    return lines


def server_module(spec: MvpSpec) -> str:
    auth_check = ""
    if has_auth(spec):
        auth_check = '''    if not os.environ.get("APP_TOKEN"):
        logger.error("APP_TOKEN environment variable is required; refusing to start")
        return 2
'''
    return f'''"""Process entrypoint. Configuration comes from the environment:

- APP_TOKEN: bearer token (required{"" if has_auth(spec) else " only when auth is enabled"})
- APP_DB:    SQLite database path (default: data.db)
- APP_PORT:  listen port (default: 8000)
"""

import logging
import os
import sys
from http.server import ThreadingHTTPServer

from app.api import ApiHandler
from app.storage import Storage

logger = logging.getLogger("{spec.product_name.lower()}")


def create_server(port=0, db_path=None):
    storage = Storage(db_path or os.environ.get("APP_DB", "data.db"))
    bind = os.environ.get("APP_BIND", "127.0.0.1")
    server = ThreadingHTTPServer((bind, port), ApiHandler)
    server.storage = storage
    return server


def main():
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(name)s %(levelname)s %(message)s",
    )
{auth_check}    port = int(os.environ.get("APP_PORT", "8000"))
    server = create_server(port=port)
    logger.info("listening on http://127.0.0.1:%s", server.server_address[1])
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        logger.info("shutting down")
    finally:
        server.server_close()
        server.storage.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''


def readme(spec: MvpSpec) -> str:
    endpoints = []
    if has_health(spec):
        endpoints.append("- `GET /health` — service status (public)")
    for entity in spec.entities:
        caps = capabilities_for(spec, entity)
        route = collection_route(entity)
        if "entity.create" in caps:
            endpoints.append(f"- `POST {route}` — create")
        if "entity.list" in caps:
            endpoints.append(f"- `GET {route}` — list (newest first)")
        if "entity.read" in caps:
            endpoints.append(f"- `GET {route}/{{id}}` — read")
        if "entity.update" in caps:
            endpoints.append(f"- `PATCH {route}/{{id}}` — update")
        if "entity.delete" in caps:
            endpoints.append(f"- `DELETE {route}/{{id}}` — delete")
    auth_note = (
        "All endpoints except `/health` require `Authorization: Bearer $APP_TOKEN`.\n"
        "A leaked token must be rotated by restarting with a new APP_TOKEN value.\n"
        if has_auth(spec)
        else ""
    )
    return f"""# {spec.product_name}

{spec.problem_statement}

Generated by PM Production Engineering OS. Single-process JSON API,
SQLite persistence, no third-party runtime dependencies.

## Run

```bash
export APP_TOKEN="$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')"
export APP_DB=data.db
export APP_PORT=8000
python3 -m app.server
```

## Endpoints

{chr(10).join(endpoints)}

{auth_note}
## Test

```bash
python3 -m unittest discover -s tests -t .
```

## Known limitations

- Single static token per deployment (single-user product by spec).
- Single process, no high-availability story (see deploy/ROLLBACK.md).
"""
