"""Code templates for the python-stdlib-crud-api stack.

Generation is capability-gated: a route or storage method exists only if the spec
declares the matching functional requirement. Output is deterministic — a pure
function of the spec.
"""

from __future__ import annotations

import json

from pmpe.domain.models import Entity, MvpSpec
from pmpe.stacks import (
    capabilities_for,
    entity_var,
    table_name,
)


def py_str(value: str) -> str:
    """A safe Python string literal for spec-controlled text (json.dumps escapes)."""
    return json.dumps(value)


def _doc_safe(text: str) -> str:
    """Spec text embedded in generated docstrings must not terminate them."""
    return text.replace("\\", "/").replace('"""', "'''")


_SQL_TYPES = {
    "string": "TEXT",
    "text": "TEXT",
    "int": "INTEGER",
    "bool": "INTEGER",
    "timestamp": "TEXT",
}


def _column_def(name: str, sql_type: str, required: bool, default: str | None) -> str:
    parts = [name, sql_type]
    if required:
        parts.append("NOT NULL")
    if default is not None:
        escaped = default.replace("'", "''")
        parts.append(f"DEFAULT '{escaped}'")
    return " ".join(parts)


def app_init_module(spec: MvpSpec) -> str:
    name = _doc_safe(spec.product_name)
    return f'"""{name} — generated by PM Production Engineering OS."""\n'


def storage_module(spec: MvpSpec) -> str:
    lines = [
        '"""Storage layer: SQLite, parameterized queries, one writer lock."""',
        "",
        "import sqlite3",
        "import threading",
        "from datetime import datetime, timezone",
        "",
        "",
        "def _utc_now():",
        "    return datetime.now(timezone.utc).isoformat()",
        "",
        "",
        "class Storage:",
        '    """SQLite-backed persistence. The db_path comes from configuration,',
        '    never from request data."""',
        "",
        "    def __init__(self, db_path):",
        "        self._conn = sqlite3.connect(db_path, check_same_thread=False)",
        "        self._conn.row_factory = sqlite3.Row",
        "        self._lock = threading.Lock()",
    ]
    for entity in spec.entities:
        columns = ", ".join(
            [
                _column_def(f.name, _SQL_TYPES.get(f.type, "TEXT"), f.required, f.default)
                for f in entity.fields
            ]
        )
        lines += [
            "        self._conn.execute(",
            f'            "CREATE TABLE IF NOT EXISTS {table_name(entity)} ("',
            '            "id INTEGER PRIMARY KEY AUTOINCREMENT, "',
            f'            "{columns}, "',
            '            "created_at TEXT NOT NULL, updated_at TEXT NOT NULL)"',
            "        )",
        ]
    lines += [
        "        self._conn.commit()",
        "",
        "    def close(self):",
        "        self._conn.close()",
    ]
    for entity in spec.entities:
        lines += _storage_entity_methods(spec, entity)
    return "\n".join(lines) + "\n"


def _storage_entity_methods(spec: MvpSpec, entity: Entity) -> list[str]:
    caps = capabilities_for(spec, entity)
    var = entity_var(entity)
    table = table_name(entity)
    field_names = [f.name for f in entity.fields]
    insert_cols = ", ".join(field_names + ["created_at", "updated_at"])
    placeholders = ", ".join(["?"] * (len(field_names) + 2))
    value_exprs: list[str] = []
    for f in entity.fields:
        if f.default is not None:
            value_exprs.append(f'fields.get("{f.name}", {py_str(f.default)})')
        else:
            value_exprs.append(f'fields.get("{f.name}")')
    values = ", ".join(value_exprs)

    lines: list[str] = []
    # get_* is always generated: create/update return the stored row through it
    lines += [
        "",
        f"    def get_{var}(self, {var}_id):",
        "        row = self._conn.execute(",
        f'            "SELECT * FROM {table} WHERE id = ?", ({var}_id,)',
        "        ).fetchone()",
        "        return dict(row) if row else None",
    ]
    if "entity.create" in caps:
        lines += [
            "",
            f"    def create_{var}(self, fields):",
            "        now = _utc_now()",
            "        with self._lock:",
            "            cur = self._conn.execute(",
            f'                "INSERT INTO {table} ({insert_cols}) "',
            f'                "VALUES ({placeholders})",',
            f"                ({values}, now, now),",
            "            )",
            "            self._conn.commit()",
            f"        return self.get_{var}(cur.lastrowid)",
        ]
    if "entity.list" in caps:
        filter_field = "status" if "status" in field_names else None
        if filter_field:
            lines += [
                "",
                f"    def list_{table}(self, {filter_field}=None):",
                f"        if {filter_field} is None:",
                "            rows = self._conn.execute(",
                f'                "SELECT * FROM {table} ORDER BY id DESC"',
                "            ).fetchall()",
                "        else:",
                "            rows = self._conn.execute(",
                f'                "SELECT * FROM {table} WHERE {filter_field} = ? '
                'ORDER BY id DESC",',
                f"                ({filter_field},),",
                "            ).fetchall()",
                "        return [dict(r) for r in rows]",
            ]
        else:
            lines += [
                "",
                f"    def list_{table}(self):",
                "        rows = self._conn.execute(",
                f'            "SELECT * FROM {table} ORDER BY id DESC"',
                "        ).fetchall()",
                "        return [dict(r) for r in rows]",
            ]
    if "entity.update" in caps:
        allowed = ", ".join(f'"{n}"' for n in field_names)
        lines += [
            "",
            f"    def update_{var}(self, {var}_id, fields):",
            f"        allowed = ({allowed},)",
            "        changes = {k: v for k, v in fields.items() if k in allowed}",
            "        if not changes:",
            f"            return self.get_{var}({var}_id)",
            '        assignments = ", ".join(k + " = ?" for k in sorted(changes))',
            "        values = [changes[k] for k in sorted(changes)]",
            "        with self._lock:",
            "            cur = self._conn.execute(",
            f'                "UPDATE {table} SET " + assignments + ", updated_at = ? '
            'WHERE id = ?",',
            f"                (*values, _utc_now(), {var}_id),",
            "            )",
            "            self._conn.commit()",
            "        if cur.rowcount == 0:",
            "            return None",
            f"        return self.get_{var}({var}_id)",
        ]
    if "entity.delete" in caps:
        lines += [
            "",
            f"    def delete_{var}(self, {var}_id):",
            "        with self._lock:",
            "            cur = self._conn.execute(",
            f'                "DELETE FROM {table} WHERE id = ?", ({var}_id,)',
            "            )",
            "            self._conn.commit()",
            "        return cur.rowcount > 0",
        ]
    return lines


def auth_module() -> str:
    return '''"""Bearer-token authentication.

The token is injected via the APP_TOKEN environment variable at deploy time.
It is never stored in code, configuration files, or logs.
"""

import hmac
import os

TOKEN_ENV = "APP_TOKEN"


def expected_token():
    return os.environ.get(TOKEN_ENV, "")


def token_from_header(header):
    if not header:
        return ""
    parts = header.split(" ", 1)
    if len(parts) != 2 or parts[0].lower() != "bearer":
        return ""
    return parts[1].strip()


def verify_token(candidate):
    expected = expected_token()
    if not expected or not candidate:
        return False
    return hmac.compare_digest(candidate, expected)
'''
