"""The synthetic demonstration: one complete engineering run over a workspace
with planted defects — every claim in the demo report backed by evidence the
real machinery produced.

Everything is labeled synthetic (PD-11: fixture agent artifacts stand in for
live Claude agents, so CI proves the admission/gate machinery deterministically)
and nothing touches a real environment (PD-09).

Planted failures and their detectors:
- code defect      eval() on operator input   -> deterministic security scanner
- conformance      FR-002 with no executed test -> executed traceability
- complexity       an unjustified factory      -> the simplicity review finding
- trajectory/drift pre-built planted fixtures  -> evaluate_trajectory / drift compare
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

import yaml

from pmpe.assurance.findings import FindingsStore
from pmpe.assurance.reconcile import OwnerDecision
from pmpe.audit.executed import build_executed_traceability
from pmpe.contracts.change_request import ChangeRequestStore
from pmpe.deployment.policy import production_readiness
from pmpe.domain.serialize import atomic_write_json
from pmpe.engineering.engine import DeploymentBlocked, EngineeringRun
from pmpe.evals.drift import compare
from pmpe.evals.trajectory import evaluate_trajectory
from pmpe.gitops.local import LocalGitAdapter
from pmpe.quality.security_scan import scan_tree
from pmpe.quality.test_evidence import TestEvidence, run_tests_with_evidence

LABEL = (
    "SYNTHETIC DEMONSTRATION — fixture agent artifacts, planted defects, "
    "no real environment touched"
)

_OWNER = "abhillash"
_HEALTH_TEST = "tests.test_health.TestHealth.test_health_returns_ok"
_CONFIG_TEST = "tests.test_config.TestConfig.test_parse_config_parses_json_without_execution"

_APP_PLANTED = '''"""Demo Pinger service (SYNTHETIC DEMO workspace — contains planted defects)."""


def parse_config(raw):
    # PLANTED DEFECT: operator-supplied configuration is executed, not parsed
    return eval(raw)  # noqa — the demo exists to catch exactly this


def health():
    return {"status": "ok"}
'''

_APP_FIXED = '''"""Demo Pinger service (SYNTHETIC DEMO workspace)."""

import json


def parse_config(raw):
    # operator-supplied configuration is parsed as data, never executed
    return json.loads(raw)


def health():
    return {"status": "ok"}
'''

_FACTORY_PLANTED = '''"""PLANTED COMPLEXITY: no requirement asks for a provider abstraction."""


class AbstractProviderFactory:
    _registry = {}

    @classmethod
    def register(cls, name, provider):
        cls._registry[name] = provider

    @classmethod
    def create(cls, name):
        return cls._registry[name]()
'''

_TEST_HEALTH = """import unittest

from app import health


class TestHealth(unittest.TestCase):
    def test_health_returns_ok(self):
        self.assertEqual(health()["status"], "ok")
"""

_TEST_CONFIG = """import unittest

from app import parse_config


class TestConfig(unittest.TestCase):
    def test_parse_config_parses_json_without_execution(self):
        self.assertEqual(parse_config('{"interval": 5}'), {"interval": 5})
"""


def build_workspace(root: Path) -> Path:
    """A git workspace with the planted code, conformance, and complexity defects."""
    root = Path(root)
    (root / "tests").mkdir(parents=True)
    (root / "deploy").mkdir()
    (root / "README.md").write_text(
        "# Demo Pinger (SYNTHETIC DEMO workspace)\n\n"
        "Generated by pmpe.demo.synthetic with deliberately planted defects —\n"
        "see examples/v2-demo/README.md.\n"
    )
    # bytecode caches are excluded from the candidate digest and must likewise
    # never dirty the git worktree (freeze rejects dirty trees)
    (root / ".gitignore").write_text("__pycache__/\n*.pyc\n")
    (root / "app.py").write_text(_APP_PLANTED)
    (root / "provider_factory.py").write_text(_FACTORY_PLANTED)
    (root / "tests" / "__init__.py").write_text("")
    (root / "tests" / "test_health.py").write_text(_TEST_HEALTH)
    (root / "deploy" / "run.sh").write_text(
        '#!/bin/sh\npython3 -c "import app; print(app.health())"\n'
    )
    (root / "deploy" / "ROLLBACK.md").write_text(
        "# Rollback\n\nRevert to the previous commit and rerun deploy/run.sh.\n"
    )
    git = LocalGitAdapter(root)
    git.init()
    git.commit_all("chore: synthetic demo workspace with planted defects")
    return root


# --- fixture agent artifacts (labeled stand-ins for live agents, PD-11) ----------------


def _architecture(contract_digest: str) -> dict[str, Any]:
    return {
        "label": "synthetic-fixture",
        "contract_digest": contract_digest,
        "components": [{"name": "service", "justifying_requirements": ["FR-001", "FR-002"]}],
        "adrs": [
            {
                "id": "ADR-001",
                "title": "Single module, stdlib only",
                "context": "two small functions, one operator",
                "decision": "one app.py, json for config parsing",
                "consequences": "no HA; acceptable per known_risks",
                "reversibility": "reversible",
            }
        ],
    }


def _plan(contract_digest: str) -> dict[str, Any]:
    base = {"component": "service", "rollback": "revert the task commit"}
    return {
        "label": "synthetic-fixture",
        "contract_digest": contract_digest,
        "tasks": [
            {
                "id": "T-001",
                "requirement_ids": ["FR-001", "FR-002"],
                "behavioural_test": "health() returns ok; parse_config() parses without exec",
                "required_capability": "backend",
                **base,
            },
            {
                "id": "T-002",
                "requirement_ids": ["FR-001", "FR-002"],
                "behavioural_test": "executed unittest coverage for AC-001 and AC-002",
                "required_capability": "test",
                **base,
            },
        ],
    }


def _routing() -> dict[str, Any]:
    from pmpe.agents.router import ALL_PROFILES

    selected = [
        {"agent": "v2-backend-engineer", "tasks": ["T-001"], "reason": "owns backend capability"},
        {"agent": "v2-test-engineer", "tasks": ["T-002"], "reason": "owns test capability"},
    ]
    used = {str(entry["agent"]) for entry in selected}
    return {
        "label": "synthetic-fixture",
        "selected": selected,
        "not_selected": [
            {"agent": name, "reason": "no task requires this capability"}
            for name in ALL_PROFILES
            if name not in used
        ],
    }


def _reviews(
    candidate: str, scan_evidence: str, coverage_evidence: str, complexity_evidence: str
) -> dict[str, list[dict[str, Any]]]:
    """The four reviewers' findings; evidence strings quote the real detectors."""
    return {
        "v2-code-reviewer": [
            {
                "title": "eval() on operator-supplied config",
                "severity": "critical",
                "blocking": True,
                "file": "app.py",
                "line": 6,
                "evidence": scan_evidence,
                "failure_mechanism": "a crafted config string executes arbitrary code",
                "mechanically_fixable": True,
                "requires_product_decision": False,
            }
        ],
        "v2-product-conformance-reviewer": [
            {
                "title": "FR-002 lacks executed test coverage",
                "severity": "high",
                "blocking": True,
                "file": "tests/test_config.py",
                "line": 1,
                "evidence": coverage_evidence,
                "failure_mechanism": "AC-002 could regress with the suite still green",
                "affected_requirement": "FR-002",
                "mechanically_fixable": True,
                "requires_product_decision": False,
            },
            {
                "title": "config format beyond JSON is undecided",
                "severity": "medium",
                "blocking": False,
                "file": "app.py",
                "line": 4,
                "evidence": "the contract specifies safe parsing (AC-002) but is silent on "
                "whether operators may supply YAML — engineering cannot decide this",
                "failure_mechanism": "choosing a format here would be a product decision "
                "made by an agent",
                "mechanically_fixable": False,
                "requires_product_decision": True,
            },
        ],
        "v2-architecture-simplicity-reviewer": [
            {
                "title": "AbstractProviderFactory has no justifying requirement",
                "severity": "medium",
                "blocking": False,
                "file": "provider_factory.py",
                "line": 4,
                "evidence": f"structure check: {complexity_evidence}; no functional "
                "requirement or architecture-pack component references providers",
                "failure_mechanism": "unjustified abstraction grows maintenance surface "
                "with zero contract value",
                "mechanically_fixable": True,
                "requires_product_decision": False,
            }
        ],
        "v2-eval-integrity-auditor": [],
    }


# --- detectors ---------------------------------------------------------------------------


def _scan_summary(workspace: Path) -> str:
    findings = scan_tree(workspace)
    if not findings:
        return "clean"
    return "; ".join(f"{f.rule} {Path(f.file).name}:{f.line} — {f.message}" for f in findings)


def _unreferenced_modules(workspace: Path) -> str:
    """Deterministic structure check: top-level modules no other module imports.

    This — not a hand-written report string — is the demo's complexity detector:
    it re-runs against the tree, so it finds the planted factory before the fix
    and comes back clean after it.
    """
    workspace = Path(workspace)
    sources = {
        path: path.read_text()
        for path in workspace.rglob("*.py")
        if "deploy" not in path.relative_to(workspace).parts
    }
    unreferenced = []
    for module in sorted(workspace.glob("*.py")):
        name = re.escape(module.stem)
        pattern = re.compile(rf"^\s*(?:import\s+{name}\b|from\s+{name}\b)", re.MULTILINE)
        if not any(pattern.search(text) for path, text in sources.items() if path != module):
            unreferenced.append(f"{module.name}: imported by no other module in the workspace")
    return "; ".join(unreferenced) if unreferenced else "clean"


def _traceability(
    evidence: TestEvidence, tests_by_requirement: dict[str, list[str]]
) -> dict[str, str]:
    report = build_executed_traceability(
        requirement_ids=["FR-001", "FR-002"],
        tests_by_requirement=tests_by_requirement,
        evidence=evidence,
        blocked_requirements=set(),
    )
    return {e.requirement_id: e.classification for e in report.entries}


# --- the demonstration ---------------------------------------------------------------------


def run_demo(
    base_dir: Path,
    *,
    contract: Path = Path("examples/v2-demo/contract.json"),
    agents_dir: Path = Path(".claude/agents"),
    evals_dir: Path = Path("evals"),
) -> dict[str, Any]:
    base_dir = Path(base_dir)
    base_dir.mkdir(parents=True, exist_ok=True)
    workspace = build_workspace(base_dir / "workspace")
    git = LocalGitAdapter(workspace)

    run = EngineeringRun.start(contract, base_dir / "run", agents_dir=agents_dir, fixture_mode=True)
    run.record_assessment(
        {"label": "synthetic-fixture", "summary": "generated demo workspace, planted defects"}
    )
    run.submit("v2-system-architect", _architecture(run.contract_digest))
    run.submit("v2-implementation-planner", _plan(run.contract_digest))
    run.submit("v2-engineer-router", _routing())
    for agent, task in (("v2-backend-engineer", "T-001"), ("v2-test-engineer", "T-002")):
        run.submit(
            agent,
            {
                "label": "synthetic-fixture",
                "task_id": task,
                "commits": [git.log()[0].sha],
                "tests_run": [_HEALTH_TEST],
                "results": "passed",
            },
        )
    run.submit(
        "v2-integration-engineer",
        {
            "label": "synthetic-fixture",
            "integrated_branches": ["main"],
            "checks_run": ["workspace unittest suite"],
            "candidate_digest": "sha256:integrator-view",
        },
    )
    candidate = run.freeze(workspace).tree_digest

    # detection with the real machinery
    scan_before = _scan_summary(workspace)
    complexity_before = _unreferenced_modules(workspace)
    evidence_before = run_tests_with_evidence(workspace)
    mapping_before = {"FR-001": [_HEALTH_TEST], "FR-002": []}
    traceability_before = _traceability(evidence_before, mapping_before)

    coverage_evidence = (
        f"executed traceability: FR-002 = {traceability_before['FR-002']} "
        "(no test is mapped to this requirement; markers would not count anyway)"
    )
    reviews = _reviews(candidate, scan_before, coverage_evidence, complexity_before)
    for reviewer, findings in reviews.items():
        run.begin_review(reviewer, workspace)
        run.submit(
            reviewer,
            {"reviewer": reviewer, "candidate_digest": candidate, "findings": findings},
        )
        run.end_review(reviewer, workspace)

    decision = OwnerDecision(status="ACCEPTED", owner=_OWNER, reason="planted defect confirmed")
    reconciliation = run.reconcile_findings(
        {"RF-001": decision, "RF-002": decision, "RF-004": decision}, owner=_OWNER
    )

    # fix ONLY the accepted findings — real edits, real commit
    (workspace / "app.py").write_text(_APP_FIXED)
    (workspace / "provider_factory.py").unlink()
    (workspace / "tests" / "test_config.py").write_text(_TEST_CONFIG)
    fix_sha = git.commit_all(
        "fix: RF-001 RF-002 RF-004 — parse config as data, add executed "
        "FR-002 coverage, drop unjustified factory"
    )
    fixed_files = {
        "RF-001": ["app.py"],
        "RF-002": ["tests/test_config.py"],
        "RF-004": ["provider_factory.py"],
    }
    run.submit(
        "v2-approved-findings-fixer",
        {
            "label": "synthetic-fixture",
            "fixed": [
                {
                    "finding_id": fid,
                    "commits": [fix_sha],
                    "checks_rerun": ["workspace suite"],
                    "changed_files": files,
                }
                for fid, files in fixed_files.items()
            ],
        },
    )

    evidence_after = run_tests_with_evidence(workspace)
    executed = len(evidence_after.executions)
    passed = sum(1 for e in evidence_after.executions if e.outcome == "passed")
    retest_detail = f"{passed}/{executed} executed tests passed"
    run.record_gates(repo=workspace, passed=evidence_after.all_passed, detail=retest_detail)
    run.freeze(workspace)
    for finding_id, verifier in (
        ("RF-001", "v2-code-reviewer"),
        ("RF-002", "v2-product-conformance-reviewer"),
        ("RF-004", "v2-architecture-simplicity-reviewer"),
    ):
        run.record_fix_verification(finding_id, verifier=verifier)

    mapping_after = {"FR-001": [_HEALTH_TEST], "FR-002": [_CONFIG_TEST]}
    traceability_after = _traceability(evidence_after, mapping_after)
    scan_after = _scan_summary(workspace)
    complexity_after = _unreferenced_modules(workspace)

    run.record_draft_pr(
        "SYNTHETIC demo draft-PR record — the demo opens no real PR (PD-08: draft only)"
    )
    deployments: dict[str, str] = {}
    for environment in ("local", "staging"):
        run.deploy(environment, repo=workspace)  # re-verifies the frozen candidate tree
        deployments[environment] = "authorized"
    # readiness attestations come from executed evidence, not assertions
    health_verified = evidence_after.by_node().get(_HEALTH_TEST) is not None
    journey_verified = evidence_after.by_node().get(_CONFIG_TEST) is not None
    readiness = production_readiness(
        workspace, health_verified=health_verified, journey_verified=journey_verified
    )
    production_blocked_reason = ""
    try:
        run.deploy(
            "production",
            repo=workspace,
            health_verified=health_verified,
            journey_verified=journey_verified,
        )
    except DeploymentBlocked as exc:
        production_blocked_reason = str(exc)
    # binary release gates evaluated from the run's own evidence (PD-01)
    release_gates = {
        "GATE-001": all(v == "VERIFIED" for v in traceability_after.values()),
        "GATE-002": scan_after == "clean",
    }
    run.record_release_report("READY_FOR_PRODUCTION_APPROVAL", gate_results=release_gates)

    # audits over the evidence that now exists
    own_violations = evaluate_trajectory(run.ledger.read_all())
    planted_ledger = (
        evals_dir / "fixtures" / "trajectory" / "planted_implement_before_architecture.jsonl"
    )
    planted_events = [
        json.loads(line) for line in planted_ledger.read_text().splitlines() if line.strip()
    ]
    planted_violations = evaluate_trajectory(planted_events)
    drift = compare(
        json.loads((evals_dir / "baselines" / "synthetic-baseline.json").read_text()),
        json.loads(
            (evals_dir / "fixtures" / "drift" / "current_hard_gate_failure.json").read_text()
        ),
        yaml.safe_load((evals_dir / "thresholds.yaml").read_text()),
    )

    store = FindingsStore(run.run_dir)
    report: dict[str, Any] = {
        "synthetic": True,
        "label": LABEL,
        "run_id": run.status()["run_id"],
        "run_dir": str(run.run_dir),
        "workspace": str(workspace),
        "planted": {
            "code_defect": "app.py parse_config() executes operator input via eval()",
            "conformance": "FR-002 shipped with no executed test",
            "complexity": "provider_factory.py AbstractProviderFactory (unjustified)",
            "trajectory": str(planted_ledger),
            "drift": "evals/fixtures/drift/current_hard_gate_failure.json",
        },
        "detected": {
            "code_defect": scan_before,
            "code_defect_after_fix": scan_after,
            "complexity": complexity_before,
            "complexity_after_fix": complexity_after,
            "planted_trajectory": "; ".join(
                f"{v.check_id}: {v.description}" for v in planted_violations
            ),
        },
        "traceability_before": traceability_before,
        "traceability_after": traceability_after,
        "reconciliation": {
            "accepted": reconciliation.accepted,
            "rejected": reconciliation.rejected,
            "duplicates": reconciliation.duplicates,
            "product_decisions": reconciliation.product_decisions,
            "open_change_requests": [
                pcr.request_id
                for pcr in ChangeRequestStore(run.run_dir).list()
                if pcr.status == "OPEN"
            ],
        },
        "fixes": [
            {
                "finding_id": f.finding_id,
                "fixed_by": f.fixed_by,
                "verified_by": f.verified_by,
                "status": f.status,
            }
            for f in store.all()
            if f.status == "VERIFIED"
        ],
        "retest": retest_detail,
        "own_run_trajectory_violations": [f"{v.check_id}: {v.description}" for v in own_violations],
        "drift_status": drift.status,
        "deployments": deployments,
        "production_blocked": bool(production_blocked_reason),
        "production_blocked_reason": production_blocked_reason,
        "production_readiness": {"ready": readiness.ready, "missing": readiness.missing},
        "release_gates": release_gates,
        "draft_pr": run.status()["draft_pr"],
        "release_verdict": run.status()["release_verdict"],
    }
    atomic_write_json(base_dir / "demo-report.json", report)
    return report
