"""One-command, evidence-bound PMOS-to-local-product quickstart."""

from __future__ import annotations

import hashlib
import subprocess
import sys
from pathlib import Path
from typing import Any

import yaml

from pmpe.contracts.authoring import (
    approve_contract_draft,
    build_contract_draft,
    load_json_object,
    verify_contract_approval,
    write_json_atomic,
)
from pmpe.contracts.canonical import canonical_digest
from pmpe.deployment.local import LocalProcessDeployer
from pmpe.domain.errors import PmpeError
from pmpe.domain.serialize import jsonable
from pmpe.engineering.candidate import tree_content_digest
from pmpe.engineering.engine import EngineeringRun
from pmpe.implementation.agent import StdlibCrudGenerator
from pmpe.implementation.workspace import write_files
from pmpe.ingestion.normalizer import normalize_spec
from pmpe.personal.executor import run_personal_execution, write_personal_execution
from pmpe.personal.runtime.demo import run_runtime_demo
from pmpe.personal.synthetic import synthetic_personal_context
from pmpe.planning.planner import EngineeringPlanner
from pmpe.review.fixer import FixAgent
from pmpe.review.reviewer import PrReviewer
from pmpe.testing.architect import TestArchitect
from pmpe.validation.validator import RequirementValidator

_APPROVER = "quickstart-product-owner"
_APPROVED_AT = "2026-08-20T00:00:00+05:30"


class FullProductError(PmpeError):
    """The full-product workflow could not produce verified local evidence."""


def _remove_generated_bytecode(workspace: Path) -> None:
    bytecode = sorted(
        (
            path
            for path in workspace.rglob("*")
            if path.is_file() and path.suffix in {".pyc", ".pyo"}
        ),
        reverse=True,
    )
    for path in bytecode:
        path.unlink()
    caches = sorted(
        (path for path in workspace.rglob("__pycache__") if path.is_dir()),
        key=lambda path: len(path.parts),
        reverse=True,
    )
    for cache in caches:
        try:
            cache.rmdir()
        except OSError as exc:
            raise FullProductError(f"generated bytecode cache is not empty: {cache}") from exc


def _contains_executable_bytecode(workspace: Path) -> bool:
    return any(
        path.name == "__pycache__" or (path.is_file() and path.suffix in {".pyc", ".pyo"})
        for path in workspace.rglob("*")
    )


def _artifact(root: Path, stage_id: str, path: Path) -> dict[str, str]:
    value = load_json_object(path)
    return {
        "artifact": path.relative_to(root).as_posix(),
        "artifact_digest": canonical_digest(value),
        "stage_id": stage_id,
        "status": "VERIFIED",
    }


def _file_digest(path: Path) -> str:
    return f"sha256:{hashlib.sha256(path.read_bytes()).hexdigest()}"


def _write_evidence_index(root: Path, directory: Path, *, report_name: str) -> Path:
    index_path = directory / "evidence-index.json"
    files = []
    for path in sorted(directory.rglob("*")):
        if path.is_symlink():
            raise FullProductError(f"evidence index refuses symbolic link: {path}")
        if not path.is_file() or path == index_path:
            continue
        files.append(
            {
                "digest": _file_digest(path),
                "path": path.relative_to(directory).as_posix(),
                "size": path.stat().st_size,
            }
        )
    if report_name not in {item["path"] for item in files}:
        raise FullProductError(f"evidence index is missing its report: {report_name}")
    write_json_atomic(
        index_path,
        {
            "directory": directory.relative_to(root).as_posix(),
            "files": files,
            "report": report_name,
            "schema_version": "1.0.0",
        },
    )
    return index_path


def _verify_evidence_index(root: Path, index: dict[str, Any]) -> dict[str, Any]:
    if set(index) != {"directory", "files", "report", "schema_version"}:
        raise FullProductError("evidence index has an unexpected shape")
    if index["schema_version"] != "1.0.0" or not isinstance(index["files"], list):
        raise FullProductError("evidence index metadata is invalid")
    root_resolved = root.resolve()
    relative_directory = Path(str(index["directory"]))
    if (
        relative_directory.is_absolute()
        or not relative_directory.parts
        or any(part in {".", ".."} for part in relative_directory.parts)
    ):
        raise FullProductError("evidence index directory is missing or escapes output")
    unresolved_directory = root
    for part in relative_directory.parts:
        unresolved_directory /= part
        if unresolved_directory.is_symlink():
            raise FullProductError(f"evidence index refuses symbolic link: {unresolved_directory}")
    directory = unresolved_directory.resolve()
    if not directory.is_relative_to(root_resolved) or not directory.is_dir():
        raise FullProductError("evidence index directory is missing or escapes output")
    declared: set[str] = set()
    for item in index["files"]:
        if not isinstance(item, dict) or set(item) != {"digest", "path", "size"}:
            raise FullProductError("evidence index entry has an unexpected shape")
        relative = str(item["path"])
        candidate = directory / relative
        path = candidate.resolve()
        if (
            relative in declared
            or candidate.is_symlink()
            or not path.is_relative_to(directory)
            or not path.is_file()
        ):
            raise FullProductError(f"evidence index path is missing or unsafe: {relative}")
        if path.stat().st_size != item["size"] or _file_digest(path) != item["digest"]:
            raise FullProductError(f"evidence index content mismatch: {relative}")
        declared.add(relative)
    actual: set[str] = set()
    index_path = directory / "evidence-index.json"
    for path in directory.rglob("*"):
        if path.is_symlink():
            raise FullProductError(f"evidence index refuses symbolic link: {path}")
        if path.is_file() and path != index_path:
            actual.add(path.relative_to(directory).as_posix())
    if declared != actual:
        raise FullProductError("evidence index does not exactly cover its retained directory")
    report = str(index["report"])
    if report not in declared:
        raise FullProductError("evidence index report is not declared")
    return load_json_object(directory / report)


def _decision_answers(repo_root: Path) -> dict[str, Any]:
    raw = yaml.safe_load((repo_root / "examples" / "taskflow_mvp_spec.yaml").read_text())
    if not isinstance(raw, dict):
        raise FullProductError("local product specification is not an object")
    spec_digest = canonical_digest(raw)
    return {
        "acceptance_criteria": raw["acceptance_criteria"],
        "approved_product_decisions": [
            {
                "id": "APD-SPEC-001",
                "decision": f"Build the exact TaskFlow specification {spec_digest}.",
            },
            {
                "id": "APD-DEPLOY-001",
                "decision": (
                    "Verify a local-process deployment; require separate approval for cloud."
                ),
            },
        ],
        "binary_release_gates": [
            {
                "id": "GATE-001",
                "description": "Every functional requirement has an executed passing test.",
            },
            {"id": "GATE-002", "description": "Zero blocking review findings."},
            {"id": "GATE-003", "description": "The local health check passes."},
            {"id": "GATE-004", "description": "The authenticated user journey passes."},
        ],
        "contract_id": "PDC-TASKFLOW-QUICKSTART-001",
        "contract_version": 1,
        "desired_outcome": raw["user_outcome"],
        "functional_requirements": raw["functional_requirements"],
        "golden_cases": [
            "Unauthenticated task requests are rejected.",
            "A task can be created, listed, completed, and read back.",
        ],
        "guardrails": raw["guardrails"],
        "known_risks": raw["risks"],
        "leading_metrics": raw["leading_metrics"],
        "non_functional_requirements": raw["non_functional_requirements"],
        "north_star_metric": raw["north_star_metric"],
        "out_of_scope": raw["non_goals"],
        "problem": raw["problem_statement"],
        "product_name": raw["product_name"],
        "required_approvals": [
            {"role": "product-owner", "for": "production deployment"},
            {"role": "security-owner", "for": "credential or authentication changes"},
        ],
        "scope": raw["scope"],
        "scored_eval_rubric": [
            {"id": "RUB-001", "criterion": "Task journey correctness", "scale": "1-5"},
            {"id": "RUB-002", "criterion": "Authentication safety", "scale": "1-5"},
        ],
        "target_user": raw["target_user"],
    }


def _write_decision_and_handoff(root: Path, repo_root: Path) -> tuple[Path, Path, Path]:
    result = build_contract_draft(_decision_answers(repo_root))
    if result.draft is None or result.draft_digest is None:
        raise FullProductError("synthetic product truth did not produce an approvable contract")
    approved = approve_contract_draft(
        result.draft,
        expected_draft_digest=result.draft_digest,
        approver=_APPROVER,
        approved_at=_APPROVED_AT,
    )
    decision = root / "decision"
    contract_path = decision / "contract.json"
    receipt_path = decision / "approval-receipt.json"
    write_json_atomic(contract_path, approved.contract)
    write_json_atomic(receipt_path, approved.receipt)
    verify_contract_approval(approved.contract, approved.receipt, expected_approver=_APPROVER)
    handoff = decision / "engineering-handoff"
    EngineeringRun.start(
        contract_path,
        handoff,
        agents_dir=repo_root / ".claude" / "agents",
        approval_receipt_path=receipt_path,
        expected_approver=_APPROVER,
    )
    return contract_path, receipt_path, handoff / "run-state.json"


def _contract_requirement_projection(contract: dict[str, Any]) -> list[dict[str, Any]]:
    return [
        {key: item[key] for key in ("id", "title", "capability", "description")}
        | ({"entity": item["entity"]} if item.get("entity") else {})
        for item in contract["functional_requirements"]
    ]


def _spec_requirement_projection(raw: dict[str, Any]) -> list[dict[str, Any]]:
    return [
        {key: item[key] for key in ("id", "title", "capability", "description")}
        | ({"entity": item["entity"]} if item.get("entity") else {})
        for item in raw["functional_requirements"]
    ]


def _assert_contract_matches_spec(contract: dict[str, Any], raw: dict[str, Any]) -> None:
    matches = (
        contract.get("product_name") == raw.get("product_name"),
        contract.get("problem") == raw.get("problem_statement"),
        contract.get("target_user") == raw.get("target_user"),
        contract.get("desired_outcome") == raw.get("user_outcome"),
        contract.get("scope") == raw.get("scope"),
        contract.get("out_of_scope") == raw.get("non_goals"),
        contract.get("acceptance_criteria") == raw.get("acceptance_criteria"),
        contract.get("non_functional_requirements") == raw.get("non_functional_requirements"),
        contract.get("north_star_metric") == raw.get("north_star_metric"),
        _contract_requirement_projection(contract) == _spec_requirement_projection(raw),
    )
    if not all(matches):
        raise FullProductError("approved product contract does not match the build specification")


def _build_review_and_deploy_local_product(
    root: Path, repo_root: Path, contract: dict[str, Any]
) -> tuple[Path, Path]:
    raw = yaml.safe_load((repo_root / "examples" / "taskflow_mvp_spec.yaml").read_text())
    if not isinstance(raw, dict):
        raise FullProductError("local product specification is not an object")
    _assert_contract_matches_spec(contract, raw)
    contract_digest = canonical_digest(contract)
    source_spec_digest = canonical_digest(raw)
    spec = normalize_spec(raw)
    validation = RequirementValidator().validate(spec)
    if not validation.ok or validation.questions:
        raise FullProductError("local product specification requires unresolved product input")
    plan = EngineeringPlanner().plan(spec)
    generated_tests = TestArchitect().design(spec, plan)
    implementation = StdlibCrudGenerator().implement(spec, plan)
    workspace = root / "local-product" / "workspace"
    workspace.mkdir(parents=True)
    write_files(workspace, generated_tests.files)
    for task in plan.tasks:
        write_files(workspace, implementation.files_by_task.get(task.id, []))
    deployer = LocalProcessDeployer()
    deployer.write_artifacts(workspace, spec)
    initial_review = PrReviewer().review(workspace, spec, plan)
    fixes = FixAgent().apply(workspace, initial_review)
    final_review = PrReviewer().review(workspace, spec, plan)
    if final_review.blocking or fixes.escalated:
        raise FullProductError("generated product has unresolved blocking review findings")
    tests = subprocess.run(
        [sys.executable, "-m", "unittest", "discover", "-s", "tests", "-t", "."],
        cwd=workspace,
        capture_output=True,
        text=True,
        timeout=120,
    )
    write_json_atomic(
        root / "local-product" / "generated-test-result.json",
        {
            "returncode": tests.returncode,
            "schema_version": "1.0.0",
            "status": "PASS" if tests.returncode == 0 else "FAIL",
        },
    )
    if tests.returncode != 0:
        raise FullProductError(f"generated product tests failed: {tests.stderr[-500:]}")
    _remove_generated_bytecode(workspace)
    candidate_digest = tree_content_digest(workspace)
    engineering_path = root / "local-product" / "engineering-verification.json"
    write_json_atomic(
        engineering_path,
        {
            "candidate_digest": candidate_digest,
            "contract_digest": contract_digest,
            "final_review": jsonable(final_review),
            "fixes": jsonable(fixes),
            "functional_requirement_ids": [item.id for item in spec.functional_requirements],
            "initial_review": jsonable(initial_review),
            "schema_version": "1.0.0",
            "source_spec_digest": source_spec_digest,
            "status": "VERIFIED",
            "tests": {
                "command": "python -m unittest discover -s tests -t .",
                "returncode": tests.returncode,
                "status": "PASS",
            },
        },
    )
    deployment = deployer.deploy(workspace, spec)
    _remove_generated_bytecode(workspace)
    if tree_content_digest(workspace) != candidate_digest:
        raise FullProductError("deployed candidate changed after engineering verification")
    deployment_path = root / "local-product" / "deployment-result.json"
    write_json_atomic(
        deployment_path,
        {
            "candidate_digest": candidate_digest,
            "contract_digest": contract_digest,
            "product_name": spec.product_name,
            "result": jsonable(deployment),
            "schema_version": "1.0.0",
            "source_spec_digest": source_spec_digest,
        },
    )
    if not (deployment.healthy and deployment.journey_passed):
        raise FullProductError(f"local product deployment failed: {deployment.details}")
    return engineering_path, deployment_path


def run_full_product_quickstart(
    output: Path, *, repo_root: Path, seed: int = 2026
) -> dict[str, Any]:
    root = Path(output)
    if root.exists() and any(root.iterdir()):
        raise FullProductError("full-product output directory must be empty")
    root.mkdir(parents=True, exist_ok=True)
    repo = Path(repo_root).resolve()

    contract_path, receipt_path, handoff_path = _write_decision_and_handoff(root, repo)

    workflows_root = root / "workflows"
    execution = run_personal_execution(synthetic_personal_context(seed))
    workflow_paths = write_personal_execution(workflows_root, execution)

    runtime_paths = run_runtime_demo(root / "runtime")
    workflow_index = _write_evidence_index(
        root, workflows_root, report_name=workflow_paths["report"].name
    )
    runtime_index = _write_evidence_index(
        root, root / "runtime", report_name=runtime_paths["report"].name
    )
    contract = load_json_object(contract_path)
    engineering_path, deployment_path = _build_review_and_deploy_local_product(root, repo, contract)

    stages = [
        _artifact(root, "decision-contract", contract_path),
        _artifact(root, "approval-receipt", receipt_path),
        _artifact(root, "engineering-handoff", handoff_path),
        _artifact(root, "workflow-execution", workflow_index),
        _artifact(root, "runtime-assurance", runtime_index),
        _artifact(root, "engineering-verification", engineering_path),
        _artifact(root, "local-deployment", deployment_path),
    ]
    manifest: dict[str, Any] = {
        "external_provider_writes": 0,
        "label": "SYNTHETIC FULL-PRODUCT QUICKSTART — LOCAL VERIFICATION ONLY",
        "manifest_digest": "",
        "pending_approvals": len(execution.approvals),
        "schema_version": "1.0.0",
        "stages": stages,
        "status": "VERIFIED_LOCAL_PRODUCT",
        "workflow_pack_count": len(execution.results),
    }
    digest_payload = dict(manifest)
    digest_payload.pop("manifest_digest")
    manifest["manifest_digest"] = canonical_digest(digest_payload)
    write_json_atomic(root / "full-product-manifest.json", manifest)
    verify_full_product_quickstart(root, expected_digest=str(manifest["manifest_digest"]))
    return manifest


def _load_stage_artifacts(root: Path, manifest: dict[str, Any]) -> dict[str, dict[str, Any]]:
    stages = manifest.get("stages")
    if not isinstance(stages, list) or len(stages) != 7:
        raise FullProductError("full-product manifest must contain all seven stages")
    artifacts: dict[str, dict[str, Any]] = {}
    root_resolved = root.resolve()
    for stage in stages:
        if not isinstance(stage, dict) or set(stage) != {
            "artifact",
            "artifact_digest",
            "stage_id",
            "status",
        }:
            raise FullProductError("full-product stage has an unexpected shape")
        stage_id = stage["stage_id"]
        if not isinstance(stage_id, str) or stage_id in artifacts or stage["status"] != "VERIFIED":
            raise FullProductError("full-product stage identity or status is invalid")
        path = (root / str(stage["artifact"])).resolve()
        if not path.is_relative_to(root_resolved):
            raise FullProductError("full-product artifact escapes its output directory")
        value = load_json_object(path)
        if canonical_digest(value) != stage["artifact_digest"]:
            raise FullProductError(f"full-product artifact digest mismatch: {stage_id}")
        artifacts[stage_id] = value
    return artifacts


def verify_full_product_quickstart(output: Path, *, expected_digest: str) -> str:
    root = Path(output)
    manifest = load_json_object(root / "full-product-manifest.json")
    expected_keys = {
        "external_provider_writes",
        "label",
        "manifest_digest",
        "pending_approvals",
        "schema_version",
        "stages",
        "status",
        "workflow_pack_count",
    }
    if set(manifest) != expected_keys:
        raise FullProductError("full-product manifest has an unexpected shape")
    claimed = manifest["manifest_digest"]
    if claimed != expected_digest:
        raise FullProductError("manifest does not match the caller's trusted expected digest")
    projection = dict(manifest)
    projection.pop("manifest_digest")
    if claimed != canonical_digest(projection):
        raise FullProductError("full-product manifest digest mismatch")
    artifacts = _load_stage_artifacts(root, manifest)
    expected_stages = {
        "approval-receipt",
        "decision-contract",
        "engineering-handoff",
        "engineering-verification",
        "local-deployment",
        "runtime-assurance",
        "workflow-execution",
    }
    if set(artifacts) != expected_stages:
        raise FullProductError("full-product manifest stage coverage is incomplete")

    contract = artifacts["decision-contract"]
    receipt = artifacts["approval-receipt"]
    verified_receipt = verify_contract_approval(contract, receipt, expected_approver=_APPROVER)
    handoff = artifacts["engineering-handoff"]
    workflows = _verify_evidence_index(root, artifacts["workflow-execution"])
    runtime = _verify_evidence_index(root, artifacts["runtime-assurance"])
    engineering = artifacts["engineering-verification"]
    deployment = artifacts["local-deployment"]
    deployment_result = deployment.get("result", {})
    contract_digest = canonical_digest(contract)
    workspace = root / "local-product" / "workspace"
    if not workspace.is_dir():
        raise FullProductError("retained local-product workspace is missing")
    if _contains_executable_bytecode(workspace):
        raise FullProductError("retained local-product workspace contains executable bytecode")
    retained_candidate_digest = tree_content_digest(workspace)
    checks = (
        manifest["schema_version"] == "1.0.0",
        manifest["status"] == "VERIFIED_LOCAL_PRODUCT",
        manifest["workflow_pack_count"] == 21,
        manifest["pending_approvals"] > 0,
        manifest["external_provider_writes"] == 0,
        handoff.get("contract", {}).get("digest") == contract_digest,
        handoff.get("approval", {}).get("receipt_digest") == verified_receipt,
        workflows.get("status") == "COMPLETED_WITH_PENDING_APPROVALS",
        workflows.get("evidence_complete") is True,
        workflows.get("unauthorized_external_actions") == 0,
        runtime.get("status") == "COMPLETED",
        runtime.get("calendar", {}).get("external_writes") == 0,
        runtime.get("learning", {}).get("installed_regression_cases") == 0,
        engineering.get("status") == "VERIFIED",
        engineering.get("contract_digest") == contract_digest,
        all(
            not finding.get("blocking", False)
            for finding in engineering.get("final_review", {}).get("findings", [])
        ),
        engineering.get("tests", {}).get("status") == "PASS",
        deployment.get("contract_digest") == contract_digest,
        deployment.get("source_spec_digest") == engineering.get("source_spec_digest"),
        deployment.get("candidate_digest") == engineering.get("candidate_digest"),
        retained_candidate_digest == engineering.get("candidate_digest"),
        deployment.get("product_name") == contract.get("product_name"),
        deployment_result.get("environment") == "local",
        deployment_result.get("healthy") is True,
        deployment_result.get("journey_passed") is True,
    )
    if not all(checks):
        raise FullProductError("full-product semantic verification failed")
    return str(claimed)
