"""One-command, evidence-bound PMOS-to-local-product quickstart."""

from __future__ import annotations

import hashlib
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

import yaml

from pmpe.contracts.authoring import (
    approve_contract_draft,
    build_contract_draft,
    load_json_object,
    verify_contract_approval,
    write_json_atomic,
)
from pmpe.contracts.canonical import canonical_digest
from pmpe.deployment.local import LocalProcessDeployer
from pmpe.domain.errors import PmpeError
from pmpe.domain.serialize import jsonable
from pmpe.engineering.candidate import tree_content_digest
from pmpe.engineering.engine import EngineeringRun
from pmpe.implementation.agent import StdlibCrudGenerator
from pmpe.implementation.workspace import write_files
from pmpe.ingestion.normalizer import normalize_spec
from pmpe.personal.executor import (
    PersonalExecution,
    run_personal_execution,
    verify_personal_execution,
    write_personal_execution,
)
from pmpe.personal.models import (
    ApprovalItem,
    EvidenceRecord,
    PersonalExecutionReport,
    PersonalWorkContract,
    TaskPacket,
    TaskResult,
)
from pmpe.personal.planner import compile_task_graph
from pmpe.personal.runtime.demo import run_runtime_demo
from pmpe.personal.runtime.models import digest_for
from pmpe.personal.runtime.registry import EventRegistry
from pmpe.personal.synthetic import synthetic_personal_context
from pmpe.planning.planner import EngineeringPlanner
from pmpe.review.fixer import FixAgent
from pmpe.review.reviewer import PrReviewer
from pmpe.testing.architect import TestArchitect
from pmpe.validation.validator import RequirementValidator

_APPROVER = "quickstart-product-owner"
_APPROVED_AT = "2026-08-20T00:00:00+05:30"
_DIGEST = re.compile(r"sha256:[0-9a-f]{64}\Z")


class FullProductError(PmpeError):
    """The full-product workflow could not produce verified local evidence."""


def _remove_generated_bytecode(workspace: Path) -> None:
    bytecode = sorted(
        (
            path
            for path in workspace.rglob("*")
            if path.is_file() and path.suffix in {".pyc", ".pyo"}
        ),
        reverse=True,
    )
    for path in bytecode:
        path.unlink()
    caches = sorted(
        (path for path in workspace.rglob("__pycache__") if path.is_dir()),
        key=lambda path: len(path.parts),
        reverse=True,
    )
    for cache in caches:
        try:
            cache.rmdir()
        except OSError as exc:
            raise FullProductError(f"generated bytecode cache is not empty: {cache}") from exc


def _contains_executable_bytecode(workspace: Path) -> bool:
    return any(
        path.name == "__pycache__" or (path.is_file() and path.suffix in {".pyc", ".pyo"})
        for path in workspace.rglob("*")
    )


def _run_retained_product_tests(workspace: Path) -> subprocess.CompletedProcess[str]:
    try:
        return subprocess.run(
            [sys.executable, "-B", "-m", "unittest", "discover", "-s", "tests", "-t", "."],
            cwd=workspace,
            capture_output=True,
            text=True,
            timeout=120,
            env={
                "PATH": "/usr/bin:/bin:/usr/local/bin",
                "PYTHONDONTWRITEBYTECODE": "1",
            },
        )
    except subprocess.TimeoutExpired as exc:
        raise FullProductError("retained candidate tests timed out") from exc


def _assert_retained_test_suite(workspace: Path, expected: dict[str, str]) -> None:
    tests_root = workspace / "tests"
    actual = {
        path.relative_to(workspace).as_posix(): path.read_text()
        for path in tests_root.rglob("*")
        if path.is_file()
    }
    if actual != expected:
        raise FullProductError("retained candidate test suite differs from generated tests")


def _artifact(root: Path, stage_id: str, path: Path) -> dict[str, str]:
    value = load_json_object(path)
    return {
        "artifact": path.relative_to(root).as_posix(),
        "artifact_digest": canonical_digest(value),
        "stage_id": stage_id,
        "status": "VERIFIED",
    }


def _file_digest(path: Path) -> str:
    return f"sha256:{hashlib.sha256(path.read_bytes()).hexdigest()}"


def _write_evidence_index(root: Path, directory: Path, *, report_name: str) -> Path:
    index_path = directory / "evidence-index.json"
    files = []
    for path in sorted(directory.rglob("*")):
        if path.is_symlink():
            raise FullProductError(f"evidence index refuses symbolic link: {path}")
        if not path.is_file() or path == index_path:
            continue
        files.append(
            {
                "digest": _file_digest(path),
                "path": path.relative_to(directory).as_posix(),
                "size": path.stat().st_size,
            }
        )
    if report_name not in {item["path"] for item in files}:
        raise FullProductError(f"evidence index is missing its report: {report_name}")
    write_json_atomic(
        index_path,
        {
            "directory": directory.relative_to(root).as_posix(),
            "files": files,
            "report": report_name,
            "schema_version": "1.0.0",
        },
    )
    return index_path


def _verify_evidence_index(root: Path, index: dict[str, Any]) -> tuple[dict[str, Any], Path]:
    if set(index) != {"directory", "files", "report", "schema_version"}:
        raise FullProductError("evidence index has an unexpected shape")
    if index["schema_version"] != "1.0.0" or not isinstance(index["files"], list):
        raise FullProductError("evidence index metadata is invalid")
    root_resolved = root.resolve()
    relative_directory = Path(str(index["directory"]))
    if (
        relative_directory.is_absolute()
        or not relative_directory.parts
        or any(part in {".", ".."} for part in relative_directory.parts)
    ):
        raise FullProductError("evidence index directory is missing or escapes output")
    unresolved_directory = root
    for part in relative_directory.parts:
        unresolved_directory /= part
        if unresolved_directory.is_symlink():
            raise FullProductError(f"evidence index refuses symbolic link: {unresolved_directory}")
    directory = unresolved_directory.resolve()
    if not directory.is_relative_to(root_resolved) or not directory.is_dir():
        raise FullProductError("evidence index directory is missing or escapes output")
    declared: set[str] = set()
    for item in index["files"]:
        if not isinstance(item, dict) or set(item) != {"digest", "path", "size"}:
            raise FullProductError("evidence index entry has an unexpected shape")
        relative = str(item["path"])
        candidate = directory / relative
        path = candidate.resolve()
        if (
            relative in declared
            or candidate.is_symlink()
            or not path.is_relative_to(directory)
            or not path.is_file()
        ):
            raise FullProductError(f"evidence index path is missing or unsafe: {relative}")
        if path.stat().st_size != item["size"] or _file_digest(path) != item["digest"]:
            raise FullProductError(f"evidence index content mismatch: {relative}")
        declared.add(relative)
    actual: set[str] = set()
    index_path = directory / "evidence-index.json"
    for path in directory.rglob("*"):
        if path.is_symlink():
            raise FullProductError(f"evidence index refuses symbolic link: {path}")
        if path.is_file() and path != index_path:
            actual.add(path.relative_to(directory).as_posix())
    if declared != actual:
        raise FullProductError("evidence index does not exactly cover its retained directory")
    report = str(index["report"])
    if report not in declared:
        raise FullProductError("evidence index report is not declared")
    return load_json_object(directory / report), directory


def _product_contract_binding(
    contract: dict[str, Any], *, stage_id: str, source_fixture: dict[str, Any]
) -> dict[str, Any]:
    return {
        "approved_contract_digest": canonical_digest(contract),
        "approved_contract_id": contract["contract_id"],
        "evidence_role": "reusable-platform-capability-assurance",
        "product_name": contract["product_name"],
        "scope_statement": (
            "PMOS control assurance prerequisite; product behavior evidence is emitted by "
            "engineering-verification and local-deployment."
        ),
        "source_fixture_digest": canonical_digest(source_fixture),
        "stage_id": stage_id,
        "transformation_id": "approved-product-contract-to-pmos-assurance-v1",
    }


def _write_product_contract_binding(
    path: Path, contract: dict[str, Any], *, stage_id: str, source_fixture: dict[str, Any]
) -> None:
    write_json_atomic(
        path,
        _product_contract_binding(contract, stage_id=stage_id, source_fixture=source_fixture),
    )


def _verify_workflow_execution_evidence(
    directory: Path, report: dict[str, Any], source_fixture: dict[str, Any]
) -> bool:
    try:
        contract = load_json_object(directory / "personal-work-contract.json")
        task_graph = load_json_object(directory / "task-graph.json")
        results = load_json_object(directory / "workflow-results.json")
        evidence = load_json_object(directory / "evidence-ledger.json")
        approvals = load_json_object(directory / "approval-outbox.json")
        mobile_review = load_json_object(directory / "mobile-review.json")
        contract_projection = dict(contract)
        contract_digest = contract_projection.pop("contract_digest")
        report_projection = dict(report)
        report_digest = report_projection.pop("report_digest")
        tasks = task_graph["tasks"]
        result_items = results["results"]
        approval_items = approvals["items"]
        packet_by_task = {item["task_id"]: item for item in tasks}

        def digest_claim_is_valid(item: dict[str, Any], field: str) -> bool:
            projection = dict(item)
            claimed_digest = projection.pop(field)
            return bool(claimed_digest == canonical_digest(projection))

        native_contract = PersonalWorkContract(
            schema_version=contract["schema_version"],
            contract_id=contract["contract_id"],
            problem=contract["problem"],
            hypothesis=contract["hypothesis"],
            proposed_answer=contract["proposed_answer"],
            target_outcome=contract["target_outcome"],
            deadline=contract["deadline"],
            north_star_metric=contract["north_star_metric"],
            leading_metrics=tuple(contract["leading_metrics"]),
            guardrails=tuple(contract["guardrails"]),
            trade_off=contract["trade_off"],
            scope=tuple(contract["scope"]),
            non_goals=tuple(contract["non_goals"]),
            workflow_ids=tuple(contract["workflow_ids"]),
            workflow_source_ids={
                workflow_id: tuple(source_ids)
                for workflow_id, source_ids in contract["workflow_source_ids"].items()
            },
            evidence_source_bindings=dict(contract["evidence_source_bindings"]),
            approval_policy_bindings=dict(contract["approval_policy_bindings"]),
            input_digest=contract["input_digest"],
            approved_by=contract["approved_by"],
            contract_digest=contract["contract_digest"],
        )
        native_packets = tuple(
            TaskPacket(
                schema_version=item["schema_version"],
                task_id=item["task_id"],
                workflow_id=item["workflow_id"],
                objective=item["objective"],
                input_refs=tuple(item["input_refs"]),
                allowed_capabilities=tuple(item["allowed_capabilities"]),
                prohibited_capabilities=tuple(item["prohibited_capabilities"]),
                depends_on=tuple(item["depends_on"]),
                definition_of_done=tuple(item["definition_of_done"]),
                budget=item["budget"],
                approval_required=tuple(item["approval_required"]),
                verification_owner=item["verification_owner"],
                contract_digest=item["contract_digest"],
                packet_digest=item["packet_digest"],
            )
            for item in tasks
        )
        native_results = tuple(
            TaskResult(
                task_id=item["task_id"],
                workflow_id=item["workflow_id"],
                status=item["status"],
                execution_batch=item["execution_batch"],
                output=item["output"],
                evidence_refs=tuple(item["evidence_refs"]),
                packet_digest=item["packet_digest"],
                result_digest=item["result_digest"],
            )
            for item in result_items
        )
        native_approvals = tuple(
            ApprovalItem(
                approval_id=item["approval_id"],
                workflow_id=item["workflow_id"],
                action_type=item["action_type"],
                target=item["target"],
                reason=item["reason"],
                reversibility=item["reversibility"],
                evidence_refs=tuple(item["evidence_refs"]),
                payload=item["payload"],
                payload_digest=item["payload_digest"],
                status=item["status"],
            )
            for item in approval_items
        )
        native_evidence = tuple(EvidenceRecord(**item) for item in evidence["records"])
        native_report = PersonalExecutionReport(
            schema_version=report["schema_version"],
            run_id=report["run_id"],
            contract_digest=report["contract_digest"],
            task_graph_digest=report["task_graph_digest"],
            status=report["status"],
            outcome=report["outcome"],
            result_digests=tuple(report["result_digests"]),
            pending_approval_ids=tuple(report["pending_approval_ids"]),
            parallel_batches=report["parallel_batches"],
            unauthorized_external_actions=report["unauthorized_external_actions"],
            evidence_complete=report["evidence_complete"],
            evidence_ledger_digest=report["evidence_ledger_digest"],
            mobile_review_digest=report["mobile_review_digest"],
            report_digest=report["report_digest"],
        )
        native_execution = PersonalExecution(
            contract=native_contract,
            packets=native_packets,
            results=native_results,
            approvals=native_approvals,
            evidence=native_evidence,
            report=native_report,
        )
        result_task_ids = [item["task_id"] for item in result_items]

        return all(
            (
                canonical_digest(source_fixture) == contract["input_digest"],
                canonical_digest(contract_projection) == contract_digest,
                report["contract_digest"] == contract_digest,
                canonical_digest(report_projection) == report_digest,
                len(packet_by_task) == len(tasks),
                all(digest_claim_is_valid(item, "packet_digest") for item in tasks),
                compile_task_graph(native_contract) == native_packets,
                task_graph["task_graph_digest"] == canonical_digest({"tasks": tasks}),
                report["task_graph_digest"] == task_graph["task_graph_digest"],
                report["evidence_ledger_digest"] == canonical_digest(evidence),
                report["mobile_review_digest"] == canonical_digest(mobile_review),
                all(digest_claim_is_valid(item, "result_digest") for item in result_items),
                len(result_task_ids) == len(set(result_task_ids)),
                set(result_task_ids) == set(packet_by_task),
                all(
                    item["task_id"] in packet_by_task
                    and item["workflow_id"] == packet_by_task[item["task_id"]]["workflow_id"]
                    and item["packet_digest"] == packet_by_task[item["task_id"]]["packet_digest"]
                    for item in result_items
                ),
                report["result_digests"] == [item["result_digest"] for item in result_items],
                all(
                    item["payload_digest"] == canonical_digest(item["payload"])
                    for item in approval_items
                ),
                report["pending_approval_ids"] == [item["approval_id"] for item in approval_items],
                verify_personal_execution(native_execution),
            )
        )
    except (AttributeError, KeyError, TypeError, ValueError):
        return False


def _verify_runtime_execution_evidence(
    directory: Path, report: dict[str, Any], source_fixture: dict[str, Any]
) -> bool:
    try:
        events = EventRegistry(directory / "runtime-events.jsonl").read()
        contract_digest = digest_for(source_fixture["contract"])
        task_digest = digest_for(source_fixture["task"])
        input_artifact_digest = digest_for(source_fixture["input_artifact"])
        proposals = load_json_object(directory / "regression-proposals.json")
        with tempfile.TemporaryDirectory(prefix="pmpe-runtime-replay-") as replay_directory:
            replay_paths = run_runtime_demo(Path(replay_directory))
            replay_source = load_json_object(replay_paths["input"])
            replay_report = load_json_object(replay_paths["report"])
            replay_proposals = load_json_object(replay_paths["proposals"])
            replay_events = EventRegistry(replay_paths["events"]).read()
        return bool(events) and all(
            (
                all(event.subject.contract_digest == contract_digest for event in events),
                all(event.subject.task_digest == task_digest for event in events),
                events[0].subject.artifact_digest == input_artifact_digest,
                report["event_count"] == len(events),
                report["event_registry_head"] == events[-1].event_digest,
                source_fixture == replay_source,
                report == replay_report,
                proposals == replay_proposals,
                [event.as_dict() for event in events]
                == [event.as_dict() for event in replay_events],
            )
        )
    except (KeyError, OSError, TypeError, ValueError):
        return False


def _load_product_spec(repo_root: Path) -> dict[str, Any]:
    raw = yaml.safe_load((repo_root / "examples" / "taskflow_mvp_spec.yaml").read_text())
    if not isinstance(raw, dict):
        raise FullProductError("local product specification is not an object")
    return raw


def _decision_answers(raw: dict[str, Any]) -> dict[str, Any]:
    spec_digest = canonical_digest(raw)
    return {
        "acceptance_criteria": raw["acceptance_criteria"],
        "approved_product_decisions": [
            {
                "id": "APD-SPEC-001",
                "decision": f"Build the exact TaskFlow specification {spec_digest}.",
            },
            {
                "id": "APD-DEPLOY-001",
                "decision": (
                    "Verify a local-process deployment; require separate approval for cloud."
                ),
            },
        ],
        "binary_release_gates": [
            {
                "id": "GATE-001",
                "description": "Every functional requirement has an executed passing test.",
            },
            {"id": "GATE-002", "description": "Zero blocking review findings."},
            {"id": "GATE-003", "description": "The local health check passes."},
            {"id": "GATE-004", "description": "The authenticated user journey passes."},
        ],
        "contract_id": "PDC-TASKFLOW-QUICKSTART-001",
        "contract_version": 1,
        "desired_outcome": raw["user_outcome"],
        "functional_requirements": raw["functional_requirements"],
        "golden_cases": [
            "Unauthenticated task requests are rejected.",
            "A task can be created, listed, completed, and read back.",
        ],
        "guardrails": raw["guardrails"],
        "known_risks": raw["risks"],
        "leading_metrics": raw["leading_metrics"],
        "non_functional_requirements": raw["non_functional_requirements"],
        "north_star_metric": raw["north_star_metric"],
        "out_of_scope": raw["non_goals"],
        "problem": raw["problem_statement"],
        "product_name": raw["product_name"],
        "required_approvals": [
            {"role": "product-owner", "for": "production deployment"},
            {"role": "security-owner", "for": "credential or authentication changes"},
        ],
        "scope": raw["scope"],
        "scored_eval_rubric": [
            {"id": "RUB-001", "criterion": "Task journey correctness", "scale": "1-5"},
            {"id": "RUB-002", "criterion": "Authentication safety", "scale": "1-5"},
        ],
        "target_user": raw["target_user"],
    }


def _write_decision_and_handoff(
    root: Path, repo_root: Path, raw_spec: dict[str, Any]
) -> tuple[Path, Path, Path]:
    result = build_contract_draft(_decision_answers(raw_spec))
    if result.draft is None or result.draft_digest is None:
        raise FullProductError("synthetic product truth did not produce an approvable contract")
    approved = approve_contract_draft(
        result.draft,
        expected_draft_digest=result.draft_digest,
        approver=_APPROVER,
        approved_at=_APPROVED_AT,
    )
    decision = root / "decision"
    contract_path = decision / "contract.json"
    receipt_path = decision / "approval-receipt.json"
    write_json_atomic(contract_path, approved.contract)
    write_json_atomic(receipt_path, approved.receipt)
    verify_contract_approval(approved.contract, approved.receipt, expected_approver=_APPROVER)
    handoff = decision / "engineering-handoff"
    EngineeringRun.start(
        contract_path,
        handoff,
        agents_dir=repo_root / ".claude" / "agents",
        approval_receipt_path=receipt_path,
        expected_approver=_APPROVER,
    )
    return contract_path, receipt_path, handoff / "run-state.json"


def _contract_requirement_projection(contract: dict[str, Any]) -> list[dict[str, Any]]:
    return [
        {key: item[key] for key in ("id", "title", "capability", "description")}
        | ({"entity": item["entity"]} if item.get("entity") else {})
        for item in contract["functional_requirements"]
    ]


def _spec_requirement_projection(raw: dict[str, Any]) -> list[dict[str, Any]]:
    return [
        {key: item[key] for key in ("id", "title", "capability", "description")}
        | ({"entity": item["entity"]} if item.get("entity") else {})
        for item in raw["functional_requirements"]
    ]


def _assert_contract_matches_spec(contract: dict[str, Any], raw: dict[str, Any]) -> None:
    source_spec_digest = canonical_digest(raw)
    approved_decisions = contract.get("approved_product_decisions")
    approved_spec_decision = (
        next(
            (
                item
                for item in approved_decisions
                if isinstance(item, dict) and item.get("id") == "APD-SPEC-001"
            ),
            None,
        )
        if isinstance(approved_decisions, list)
        else None
    )
    matches = (
        isinstance(approved_spec_decision, dict),
        isinstance(approved_spec_decision, dict)
        and approved_spec_decision.get("decision")
        == f"Build the exact TaskFlow specification {source_spec_digest}.",
        contract.get("product_name") == raw.get("product_name"),
        contract.get("problem") == raw.get("problem_statement"),
        contract.get("target_user") == raw.get("target_user"),
        contract.get("desired_outcome") == raw.get("user_outcome"),
        contract.get("scope") == raw.get("scope"),
        contract.get("out_of_scope") == raw.get("non_goals"),
        contract.get("acceptance_criteria") == raw.get("acceptance_criteria"),
        contract.get("non_functional_requirements") == raw.get("non_functional_requirements"),
        contract.get("north_star_metric") == raw.get("north_star_metric"),
        _contract_requirement_projection(contract) == _spec_requirement_projection(raw),
    )
    if not all(matches):
        raise FullProductError("approved product contract does not match the build specification")


def _build_review_and_deploy_local_product(
    root: Path, contract: dict[str, Any], raw: dict[str, Any]
) -> tuple[Path, Path]:
    _assert_contract_matches_spec(contract, raw)
    contract_digest = canonical_digest(contract)
    source_spec_digest = canonical_digest(raw)
    spec = normalize_spec(raw)
    validation = RequirementValidator().validate(spec)
    if not validation.ok or validation.questions:
        raise FullProductError("local product specification requires unresolved product input")
    plan = EngineeringPlanner().plan(spec)
    generated_tests = TestArchitect().design(spec, plan)
    implementation = StdlibCrudGenerator().implement(spec, plan)
    workspace = root / "local-product" / "workspace"
    workspace.mkdir(parents=True)
    write_files(workspace, generated_tests.files)
    for task in plan.tasks:
        write_files(workspace, implementation.files_by_task.get(task.id, []))
    deployer = LocalProcessDeployer()
    deployer.write_artifacts(workspace, spec)
    initial_review = PrReviewer().review(workspace, spec, plan)
    fixes = FixAgent().apply(workspace, initial_review)
    final_review = PrReviewer().review(workspace, spec, plan)
    if final_review.blocking or fixes.escalated:
        raise FullProductError("generated product has unresolved blocking review findings")
    tests = subprocess.run(
        [sys.executable, "-m", "unittest", "discover", "-s", "tests", "-t", "."],
        cwd=workspace,
        capture_output=True,
        text=True,
        timeout=120,
    )
    if tests.returncode != 0:
        write_json_atomic(
            root / "local-product" / "generated-test-result.json",
            {
                "returncode": tests.returncode,
                "schema_version": "1.0.0",
                "status": "FAIL",
            },
        )
        raise FullProductError(f"generated product tests failed: {tests.stderr[-500:]}")
    _remove_generated_bytecode(workspace)
    candidate_digest = tree_content_digest(workspace)
    generated_test_result = {
        "candidate_digest": candidate_digest,
        "returncode": tests.returncode,
        "schema_version": "1.0.0",
        "status": "PASS",
    }
    write_json_atomic(root / "local-product" / "generated-test-result.json", generated_test_result)
    engineering_path = root / "local-product" / "engineering-verification.json"
    write_json_atomic(
        engineering_path,
        {
            "candidate_digest": candidate_digest,
            "contract_digest": contract_digest,
            "final_review": jsonable(final_review),
            "fixes": jsonable(fixes),
            "functional_requirement_ids": [item.id for item in spec.functional_requirements],
            "generated_test_result_digest": canonical_digest(generated_test_result),
            "initial_review": jsonable(initial_review),
            "schema_version": "1.0.0",
            "source_spec": raw,
            "source_spec_digest": source_spec_digest,
            "status": "VERIFIED",
            "tests": {
                "command": "python -m unittest discover -s tests -t .",
                "returncode": tests.returncode,
                "status": "PASS",
            },
        },
    )
    deployment = deployer.deploy(workspace, spec)
    _remove_generated_bytecode(workspace)
    if tree_content_digest(workspace) != candidate_digest:
        raise FullProductError("deployed candidate changed after engineering verification")
    deployment_path = root / "local-product" / "deployment-result.json"
    write_json_atomic(
        deployment_path,
        {
            "candidate_digest": candidate_digest,
            "contract_digest": contract_digest,
            "product_name": spec.product_name,
            "result": jsonable(deployment),
            "schema_version": "1.0.0",
            "source_spec_digest": source_spec_digest,
        },
    )
    if not (deployment.healthy and deployment.journey_passed):
        raise FullProductError(f"local product deployment failed: {deployment.details}")
    return engineering_path, deployment_path


def _run_full_product_quickstart(
    output: Path, *, repo_root: Path, seed: int = 2026
) -> dict[str, Any]:
    root = Path(output)
    if root.is_symlink():
        raise FullProductError("full-product output must be a directory")
    if root.exists():
        if not root.is_dir():
            raise FullProductError("full-product output must be a directory")
        if any(root.iterdir()):
            raise FullProductError("full-product output directory must be empty")
    root.mkdir(parents=True, exist_ok=True)
    repo = Path(repo_root).resolve()
    raw_spec = _load_product_spec(repo)

    contract_path, receipt_path, handoff_path = _write_decision_and_handoff(root, repo, raw_spec)

    contract = load_json_object(contract_path)
    workflows_root = root / "workflows"
    personal_context = synthetic_personal_context(seed)
    execution = run_personal_execution(personal_context)
    workflow_paths = write_personal_execution(workflows_root, execution)
    write_json_atomic(workflows_root / "synthetic-personal-input.json", personal_context)
    _write_product_contract_binding(
        workflows_root / "product-contract-binding.json",
        contract,
        stage_id="workflow-execution",
        source_fixture=personal_context,
    )

    runtime_paths = run_runtime_demo(root / "runtime")
    runtime_context = load_json_object(runtime_paths["input"])
    _write_product_contract_binding(
        root / "runtime" / "product-contract-binding.json",
        contract,
        stage_id="runtime-assurance",
        source_fixture=runtime_context,
    )
    workflow_index = _write_evidence_index(
        root, workflows_root, report_name=workflow_paths["report"].name
    )
    runtime_index = _write_evidence_index(
        root, root / "runtime", report_name=runtime_paths["report"].name
    )
    engineering_path, deployment_path = _build_review_and_deploy_local_product(
        root, contract, raw_spec
    )

    stages = [
        _artifact(root, "decision-contract", contract_path),
        _artifact(root, "approval-receipt", receipt_path),
        _artifact(root, "engineering-handoff", handoff_path),
        _artifact(root, "workflow-execution", workflow_index),
        _artifact(root, "runtime-assurance", runtime_index),
        _artifact(root, "engineering-verification", engineering_path),
        _artifact(root, "local-deployment", deployment_path),
    ]
    manifest: dict[str, Any] = {
        "external_provider_writes": 0,
        "label": "SYNTHETIC FULL-PRODUCT QUICKSTART — LOCAL VERIFICATION ONLY",
        "manifest_digest": "",
        "pending_approvals": len(execution.approvals),
        "schema_version": "1.0.0",
        "stages": stages,
        "status": "VERIFIED_LOCAL_PRODUCT",
        "workflow_pack_count": len(execution.results),
    }
    digest_payload = dict(manifest)
    digest_payload.pop("manifest_digest")
    manifest["manifest_digest"] = canonical_digest(digest_payload)
    write_json_atomic(root / "full-product-manifest.json", manifest)
    verify_full_product_quickstart(root, expected_digest=str(manifest["manifest_digest"]))
    return manifest


def run_full_product_quickstart(
    output: Path, *, repo_root: Path, seed: int = 2026
) -> dict[str, Any]:
    """Run the quickstart and normalize invalid input/filesystem failures."""

    try:
        return _run_full_product_quickstart(output, repo_root=repo_root, seed=seed)
    except FullProductError:
        raise
    except (AttributeError, KeyError, OSError, TypeError, ValueError, yaml.YAMLError) as exc:
        raise FullProductError("full-product quickstart input or output is invalid") from exc


def _load_stage_artifacts(root: Path, manifest: dict[str, Any]) -> dict[str, dict[str, Any]]:
    stages = manifest.get("stages")
    if not isinstance(stages, list) or len(stages) != 7:
        raise FullProductError("full-product manifest must contain all seven stages")
    artifacts: dict[str, dict[str, Any]] = {}
    root_resolved = root.resolve()
    for stage in stages:
        if not isinstance(stage, dict) or set(stage) != {
            "artifact",
            "artifact_digest",
            "stage_id",
            "status",
        }:
            raise FullProductError("full-product stage has an unexpected shape")
        stage_id = stage["stage_id"]
        if not isinstance(stage_id, str) or stage_id in artifacts or stage["status"] != "VERIFIED":
            raise FullProductError("full-product stage identity or status is invalid")
        relative_artifact = Path(str(stage["artifact"]))
        if (
            relative_artifact.is_absolute()
            or not relative_artifact.parts
            or any(part in {".", ".."} for part in relative_artifact.parts)
        ):
            raise FullProductError("full-product artifact escapes its output directory")
        unresolved_path = root
        for part in relative_artifact.parts:
            unresolved_path /= part
            if unresolved_path.is_symlink():
                raise FullProductError(
                    f"full-product artifact refuses symbolic link: {unresolved_path}"
                )
        path = unresolved_path.resolve()
        if not path.is_relative_to(root_resolved):
            raise FullProductError("full-product artifact escapes its output directory")
        value = load_json_object(path)
        if canonical_digest(value) != stage["artifact_digest"]:
            raise FullProductError(f"full-product artifact digest mismatch: {stage_id}")
        artifacts[stage_id] = value
    return artifacts


def _verify_full_product_quickstart(output: Path, *, expected_digest: str) -> str:
    root = Path(output)
    manifest_path = root / "full-product-manifest.json"
    if manifest_path.is_symlink():
        raise FullProductError("full-product manifest refuses symbolic link")
    manifest = load_json_object(manifest_path)
    expected_keys = {
        "external_provider_writes",
        "label",
        "manifest_digest",
        "pending_approvals",
        "schema_version",
        "stages",
        "status",
        "workflow_pack_count",
    }
    if set(manifest) != expected_keys:
        raise FullProductError("full-product manifest has an unexpected shape")
    if not (
        isinstance(manifest["label"], str)
        and isinstance(manifest["manifest_digest"], str)
        and type(manifest["external_provider_writes"]) is int
        and type(manifest["pending_approvals"]) is int
        and isinstance(manifest["schema_version"], str)
        and isinstance(manifest["status"], str)
        and type(manifest["workflow_pack_count"]) is int
    ):
        raise FullProductError("full-product manifest value types are invalid")
    claimed = manifest["manifest_digest"]
    if claimed != expected_digest:
        raise FullProductError("manifest does not match the caller's trusted expected digest")
    projection = dict(manifest)
    projection.pop("manifest_digest")
    if claimed != canonical_digest(projection):
        raise FullProductError("full-product manifest digest mismatch")
    artifacts = _load_stage_artifacts(root, manifest)
    expected_stages = {
        "approval-receipt",
        "decision-contract",
        "engineering-handoff",
        "engineering-verification",
        "local-deployment",
        "runtime-assurance",
        "workflow-execution",
    }
    if set(artifacts) != expected_stages:
        raise FullProductError("full-product manifest stage coverage is incomplete")

    contract = artifacts["decision-contract"]
    receipt = artifacts["approval-receipt"]
    verified_receipt = verify_contract_approval(contract, receipt, expected_approver=_APPROVER)
    handoff = artifacts["engineering-handoff"]
    handoff_contract = handoff.get("contract")
    handoff_approval = handoff.get("approval")
    if not isinstance(handoff_contract, dict) or not isinstance(handoff_approval, dict):
        raise FullProductError("engineering handoff contract or approval is not an object")
    workflows, workflows_directory = _verify_evidence_index(root, artifacts["workflow-execution"])
    runtime, runtime_directory = _verify_evidence_index(root, artifacts["runtime-assurance"])
    engineering = artifacts["engineering-verification"]
    deployment = artifacts["local-deployment"]
    deployment_result = deployment.get("result")
    if not isinstance(deployment_result, dict):
        raise FullProductError("local deployment result is not an object")
    pending_approval_ids = workflows.get("pending_approval_ids")
    if not isinstance(pending_approval_ids, list):
        raise FullProductError("workflow report pending approvals are malformed")
    final_review = engineering.get("final_review")
    if not isinstance(final_review, dict):
        raise FullProductError("engineering final review is not an object")
    final_findings = final_review.get("findings")
    if not isinstance(final_findings, list) or any(
        not isinstance(finding, dict) for finding in final_findings
    ):
        raise FullProductError("engineering final review findings are malformed")
    engineering_tests = engineering.get("tests")
    if not isinstance(engineering_tests, dict):
        raise FullProductError("engineering test summary is not an object")
    retained_source_spec = engineering.get("source_spec")
    if not isinstance(retained_source_spec, dict):
        raise FullProductError("engineering source specification is not an object")
    generated_test_result_path = root / "local-product" / "generated-test-result.json"
    if generated_test_result_path.is_symlink():
        raise FullProductError("generated test result refuses symbolic link")
    generated_test_result_resolved = generated_test_result_path.resolve()
    if not generated_test_result_resolved.is_relative_to(root.resolve()):
        raise FullProductError("generated test result escapes output")
    generated_test_result = load_json_object(generated_test_result_resolved)
    contract_digest = canonical_digest(contract)
    unresolved_workspace = root / "local-product" / "workspace"
    if any(candidate.is_symlink() for candidate in (root / "local-product", unresolved_workspace)):
        raise FullProductError("retained local-product workspace refuses symbolic link")
    workspace = unresolved_workspace.resolve()
    if not workspace.is_relative_to(root.resolve()) or not workspace.is_dir():
        raise FullProductError("retained local-product workspace is missing")
    if _contains_executable_bytecode(workspace):
        raise FullProductError("retained local-product workspace contains executable bytecode")
    if any(path.is_symlink() for path in workspace.rglob("*")):
        raise FullProductError("retained local-product workspace refuses symbolic link")
    retained_candidate_digest = tree_content_digest(workspace)
    source_spec_digest = engineering.get("source_spec_digest")
    _assert_contract_matches_spec(contract, retained_source_spec)
    replay_spec = normalize_spec(retained_source_spec)
    replay_validation = RequirementValidator().validate(replay_spec)
    if not replay_validation.ok or replay_validation.questions:
        raise FullProductError("retained source specification no longer validates")
    replay_plan = EngineeringPlanner().plan(replay_spec)
    generated_tests = TestArchitect().design(replay_spec, replay_plan)
    _assert_retained_test_suite(
        workspace,
        {generated_file.path: generated_file.content for generated_file in generated_tests.files},
    )
    replayed_tests = _run_retained_product_tests(workspace)
    if replayed_tests.returncode != 0:
        raise FullProductError("retained candidate tests failed")
    if tree_content_digest(workspace) != retained_candidate_digest:
        raise FullProductError("retained candidate tests changed the workspace")
    if _contains_executable_bytecode(workspace):
        raise FullProductError("retained candidate tests emitted executable bytecode")
    try:
        replayed_deployment = LocalProcessDeployer().deploy(workspace, replay_spec)
    finally:
        _remove_generated_bytecode(workspace)
    if tree_content_digest(workspace) != retained_candidate_digest:
        raise FullProductError("retained candidate journey changed the workspace")
    if not (replayed_deployment.healthy and replayed_deployment.journey_passed):
        raise FullProductError("retained candidate authenticated journey failed")
    replay_review = jsonable(PrReviewer().review(workspace, replay_spec, replay_plan))
    approved_decisions = contract.get("approved_product_decisions")
    approved_spec_decision = (
        next(
            (
                item
                for item in approved_decisions
                if isinstance(item, dict) and item.get("id") == "APD-SPEC-001"
            ),
            None,
        )
        if isinstance(approved_decisions, list)
        else None
    )
    checks = (
        manifest["schema_version"] == "1.0.0",
        manifest["status"] == "VERIFIED_LOCAL_PRODUCT",
        manifest["workflow_pack_count"] == 21,
        manifest["pending_approvals"] == len(pending_approval_ids),
        manifest["external_provider_writes"] == 0,
        handoff_contract.get("digest") == contract_digest,
        handoff_approval.get("receipt_digest") == verified_receipt,
        load_json_object(workflows_directory / "product-contract-binding.json")
        == _product_contract_binding(
            contract,
            stage_id="workflow-execution",
            source_fixture=load_json_object(workflows_directory / "synthetic-personal-input.json"),
        ),
        _verify_workflow_execution_evidence(
            workflows_directory,
            workflows,
            load_json_object(workflows_directory / "synthetic-personal-input.json"),
        ),
        workflows.get("status") == "COMPLETED_WITH_PENDING_APPROVALS",
        workflows.get("evidence_complete") is True,
        workflows.get("unauthorized_external_actions") == 0,
        load_json_object(runtime_directory / "product-contract-binding.json")
        == _product_contract_binding(
            contract,
            stage_id="runtime-assurance",
            source_fixture=load_json_object(runtime_directory / "synthetic-runtime-input.json"),
        ),
        _verify_runtime_execution_evidence(
            runtime_directory,
            runtime,
            load_json_object(runtime_directory / "synthetic-runtime-input.json"),
        ),
        runtime.get("status") == "COMPLETED",
        runtime.get("calendar", {}).get("external_writes") == 0,
        runtime.get("learning", {}).get("installed_regression_cases") == 0,
        engineering.get("status") == "VERIFIED",
        engineering.get("contract_digest") == contract_digest,
        isinstance(source_spec_digest, str) and _DIGEST.fullmatch(source_spec_digest) is not None,
        canonical_digest(retained_source_spec) == source_spec_digest,
        isinstance(approved_spec_decision, dict),
        isinstance(approved_spec_decision, dict)
        and approved_spec_decision.get("decision")
        == f"Build the exact TaskFlow specification {source_spec_digest}.",
        replay_review == final_review,
        all(not finding.get("blocking", False) for finding in final_findings),
        engineering_tests.get("status") == "PASS",
        generated_test_result.get("status") == "PASS",
        generated_test_result.get("returncode") == 0,
        generated_test_result.get("candidate_digest") == engineering.get("candidate_digest"),
        generated_test_result.get("candidate_digest") == retained_candidate_digest,
        canonical_digest(generated_test_result) == engineering.get("generated_test_result_digest"),
        deployment.get("contract_digest") == contract_digest,
        deployment.get("source_spec_digest") == engineering.get("source_spec_digest"),
        deployment.get("candidate_digest") == engineering.get("candidate_digest"),
        retained_candidate_digest == engineering.get("candidate_digest"),
        deployment.get("product_name") == contract.get("product_name"),
        deployment_result.get("environment") == "local",
        deployment_result.get("healthy") is True,
        deployment_result.get("journey_passed") is True,
    )
    if not all(checks):
        raise FullProductError("full-product semantic verification failed")
    return str(claimed)


def verify_full_product_quickstart(output: Path, *, expected_digest: str) -> str:
    """Verify a retained bundle and normalize malformed evidence to a fail-closed error."""

    try:
        return _verify_full_product_quickstart(output, expected_digest=expected_digest)
    except FullProductError:
        raise
    except (AttributeError, KeyError, OSError, TypeError, ValueError) as exc:
        raise FullProductError("full-product evidence is malformed") from exc
