"""Regression contract for the audit-safe Vite frontend migration."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
FRONTEND = ROOT / "products" / "pm-evals-web" / "frontend"
CI_WORKFLOW = ROOT / ".github" / "workflows" / "ci.yml"
PREVIEW = ROOT / "products" / "pm-evals-web" / "scripts" / "preview.sh"


def _manifest() -> dict[str, object]:
    return json.loads((FRONTEND / "package.json").read_text())


def test_manifest_uses_stable_vite_and_audit_safe_types_only_codegen() -> None:
    manifest = _manifest()
    dependencies = manifest["dependencies"]
    dev_dependencies = manifest["devDependencies"]
    scripts = manifest["scripts"]

    assert isinstance(dependencies, dict)
    assert isinstance(dev_dependencies, dict)
    assert isinstance(scripts, dict)
    assert dependencies["react"].startswith("19.")
    assert dependencies["react-dom"].startswith("19.")
    assert dev_dependencies["vite"] == "8.1.5"
    assert dev_dependencies["@hey-api/openapi-ts"] == "0.97.0"
    assert "next" not in dependencies
    assert "openapi-typescript" not in dev_dependencies
    assert "@redocly/openapi-core" not in dev_dependencies
    assert scripts["build"] == "vite build && node scripts/write-build-id.mjs"
    assert scripts["start"] == "vite preview --host 0.0.0.0 --port 3000"
    assert scripts["generate:api-types"] == (
        "openapi-ts -i ../backend/openapi.json -o src/lib/api-types "
        "-p @hey-api/typescript --no-log-file"
    )


def test_spa_entrypoint_and_vite_proxy_preserve_root_and_api_urls() -> None:
    index = (FRONTEND / "index.html").read_text()
    main = (FRONTEND / "src" / "main.tsx").read_text()
    vite = (FRONTEND / "vite.config.ts").read_text()

    assert '<div id="root"></div>' in index
    assert 'src="/src/main.tsx"' in index
    assert "createRoot" in main
    assert 'from "@/app/page"' in main
    assert 'import "@/app/globals.css"' in main
    assert '"/api"' in vite
    assert "BACKEND_URL" in vite
    assert "server:" in vite
    assert "preview:" in vite
    assert "next" not in (index + main + vite).lower()


def test_container_and_local_preview_serve_dist_without_next_runtime() -> None:
    dockerfile = (FRONTEND / "Dockerfile").read_text()
    preview = PREVIEW.read_text()

    assert "FROM nginx:" in dockerfile
    assert "COPY --from=build /app/dist" in dockerfile
    assert "BACKEND_URL" in dockerfile
    assert "/usr/share/nginx/html/BUILD_ID" in dockerfile
    assert "npm run build" in preview
    assert "npm run start" in preview
    assert "dist/BUILD_ID" in preview
    assert "next" not in (dockerfile + preview).lower()


def test_ci_build_and_preview_contract_has_no_next_specific_path() -> None:
    workflow = CI_WORKFLOW.read_text()

    assert "npm run build" in workflow
    assert "npx next build" not in workflow
    assert ".next/BUILD_ID" not in workflow
    assert "/usr/share/nginx/html/BUILD_ID" in workflow


def test_lock_and_generated_surface_exclude_retired_dependency_chains() -> None:
    lock = json.loads((FRONTEND / "package-lock.json").read_text())
    packages = lock["packages"]
    generated = FRONTEND / "src" / "lib" / "api-types" / "types.gen.ts"

    assert isinstance(packages, dict)
    assert "node_modules/next" not in packages
    assert "node_modules/openapi-typescript" not in packages
    assert "node_modules/@redocly/openapi-core" not in packages
    assert "node_modules/@hey-api/openapi-ts" in packages
    assert generated.is_file()
    assert "auto-generated by @hey-api/openapi-ts" in generated.read_text()
